/**
 * i18n dictionary: `ai.*` (1 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"ai.defaultModel": "默认模型",
};

export const en: Record<string, string> = {
	"ai.defaultModel": "Default model",
};
