/**
 * i18n dictionary: `auth.*` (8 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"auth.2fa-disable": "关闭两步验证",
	"auth.2fa-enable": "开启两步验证",
	"auth.change-password": "修改密码",
	"auth.login": "登录",
	"auth.logout": "退出登录",
	"auth.password": "密码",
	"auth.two-factor": "两步验证",
	"auth.username": "用户名",
};

export const en: Record<string, string> = {
	"auth.2fa-disable": "Disable 2FA",
	"auth.2fa-enable": "Enable 2FA",
	"auth.change-password": "Change Password",
	"auth.login": "Login",
	"auth.logout": "Sign Out",
	"auth.password": "Password",
	"auth.two-factor": "Two-Factor Auth",
	"auth.username": "Username",
};
