/**
 * i18n dictionary: `auth.*` (27 keys).
 *
 * Shared across the login + account/security + 2FA settings surface.
 * Keys cover login labels, password change action, and the two-factor
 * setup/disable panel copy (R10H drive-by — closed the bottom-of-coverage
 * `src/components/two-factor-settings.tsx` module at the same time).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"auth.2fa-cancel": "取消",
	"auth.2fa-code-label": "6位验证码",
	"auth.2fa-confirm-disable": "确认关闭",
	"auth.2fa-confirm-enable": "确认启用",
	"auth.2fa-current-code-label": "当前验证码",
	"auth.2fa-disable": "关闭两步验证",
	"auth.2fa-disable-description": "两步验证已启用。如需关闭，请输入验证器 App 中的当前验证码。",
	"auth.2fa-disable-instruction": "输入验证器 App 中的当前验证码以关闭两步验证：",
	"auth.2fa-disabled": "未启用",
	"auth.2fa-enable": "开启两步验证",
	"auth.2fa-enabled": "已启用",
	"auth.2fa-enter-code-instruction": "2. 输入验证器 App 中显示的6位验证码：",
	"auth.2fa-error-code-length": "请输入6位验证码",
	"auth.2fa-error-invalid-code": "验证码错误，请重试",
	"auth.2fa-error-request-failed": "请求失败",
	"auth.2fa-generating": "生成中...",
	"auth.2fa-scan-qr-instruction": "1. 使用验证器 App（如 Google Authenticator、Microsoft Authenticator）扫描下方二维码",
	"auth.2fa-secret-label": "密钥（手动输入）：",
	"auth.2fa-section-title": "🔐 两步验证 (2FA)",
	"auth.2fa-setup-description": "启用两步验证后，登录时需要输入验证器 App 生成的6位动态验证码，增强账户安全性。",
	"auth.2fa-verifying": "验证中...",
	"auth.change-password": "修改密码",
	"auth.login": "登录",
	"auth.logout": "退出登录",
	"auth.two-factor": "两步验证",
};

export const en: Record<string, string> = {
	"auth.2fa-cancel": "Cancel",
	"auth.2fa-code-label": "6-digit code",
	"auth.2fa-confirm-disable": "Confirm disable",
	"auth.2fa-confirm-enable": "Confirm enable",
	"auth.2fa-current-code-label": "Current code",
	"auth.2fa-disable": "Disable 2FA",
	"auth.2fa-disable-description": "Two-factor authentication is enabled. To turn it off, enter the current code from your authenticator app.",
	"auth.2fa-disable-instruction": "Enter the current code from your authenticator app to disable two-factor authentication:",
	"auth.2fa-disabled": "Disabled",
	"auth.2fa-enable": "Enable 2FA",
	"auth.2fa-enabled": "Enabled",
	"auth.2fa-enter-code-instruction": "2. Enter the 6-digit code shown in your authenticator app:",
	"auth.2fa-error-code-length": "Please enter a 6-digit code",
	"auth.2fa-error-invalid-code": "Incorrect code, please try again",
	"auth.2fa-error-request-failed": "Request failed",
	"auth.2fa-generating": "Generating...",
	"auth.2fa-scan-qr-instruction": "1. Scan the QR code below with your authenticator app (e.g. Google Authenticator, Microsoft Authenticator)",
	"auth.2fa-secret-label": "Secret (manual entry):",
	"auth.2fa-section-title": "🔐 Two-factor authentication (2FA)",
	"auth.2fa-setup-description": "After enabling two-factor authentication, you will need a 6-digit code from your authenticator app at sign-in to strengthen account security.",
	"auth.2fa-verifying": "Verifying...",
	"auth.change-password": "Change Password",
	"auth.login": "Login",
	"auth.logout": "Sign Out",
	"auth.two-factor": "Two-Factor Auth",
};
