/**
 * i18n dictionary: `docker.*` (8 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"docker.exited": "已停止",
	"docker.logs": "日志",
	"docker.remove": "删除",
	"docker.restart": "重启",
	"docker.running": "运行中",
	"docker.start": "启动",
	"docker.stop": "停止",
	"docker.title": "Docker 容器",
};

export const en: Record<string, string> = {
	"docker.exited": "Exited",
	"docker.logs": "Logs",
	"docker.remove": "Remove",
	"docker.restart": "Restart",
	"docker.running": "Running",
	"docker.start": "Start",
	"docker.stop": "Stop",
	"docker.title": "Docker Containers",
};
