/**
 * i18n dictionary: `error.*` (4 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"error.back-home": "返回首页",
	"error.digest-label": "错误标识:",
	"error.title": "页面加载出错",
	"error.unknown": "发生了未知错误",
};

export const en: Record<string, string> = {
	"error.back-home": "Back to home",
	"error.digest-label": "Error ID:",
	"error.title": "Page failed to load",
	"error.unknown": "An unknown error occurred",
};
