/**
 * i18n dictionary: `error.*` (7 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"error.back-home": "返回首页",
	"error.digest-label": "错误标识:",
	"error.hard-refresh": "硬刷新",
	"error.health-check": "系统自检",
	"error.routeDescription": "当前页面遇到了异常，已保留现场信息。你可以重试，或稍后从系统自检/日志中继续排查。",
	"error.title": "页面加载出错",
	"error.unknown": "发生了未知错误",
};

export const en: Record<string, string> = {
	"error.back-home": "Back to home",
	"error.digest-label": "Error ID:",
	"error.hard-refresh": "Hard refresh",
	"error.health-check": "System health check",
	"error.routeDescription": "The current page hit an error and the trace has been preserved. You can retry, or check the system health and logs.",
	"error.title": "Page failed to load",
	"error.unknown": "An unknown error occurred",
};
