/**
 * i18n dictionary: `imageBed.*` (14 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"imageBed.toast.batchError": "批量操作出错",
	"imageBed.toast.copyFailed": "复制失败",
	"imageBed.toast.deleteError": "删除出错",
	"imageBed.toast.deleted": "✅ 已删除",
	"imageBed.toast.fetchListFailed": "获取图片列表失败",
	"imageBed.toast.fetchNodesFailed": "获取存储节点失败",
	"imageBed.toast.fetchStatsFailed": "获取统计信息失败",
	"imageBed.toast.htmlCopied": "✅ HTML 已复制",
	"imageBed.toast.markdownCopied": "✅ Markdown 已复制",
	"imageBed.toast.noPublishNodes": "暂无可发布的存储节点",
	"imageBed.toast.publishError": "发布出错",
	"imageBed.toast.published": "✅ 从云盘发布成功",
	"imageBed.toast.selectFirst": "请先选择图片",
	"imageBed.toast.urlCopied": "✅ 外链已复制",
};

export const en: Record<string, string> = {
	"imageBed.toast.batchError": "Batch operation failed",
	"imageBed.toast.copyFailed": "Copy failed",
	"imageBed.toast.deleteError": "Delete failed",
	"imageBed.toast.deleted": "✅ Deleted",
	"imageBed.toast.fetchListFailed": "Failed to load image list",
	"imageBed.toast.fetchNodesFailed": "Failed to load storage nodes",
	"imageBed.toast.fetchStatsFailed": "Failed to load statistics",
	"imageBed.toast.htmlCopied": "✅ HTML copied",
	"imageBed.toast.markdownCopied": "✅ Markdown copied",
	"imageBed.toast.noPublishNodes": "No storage nodes available for publishing",
	"imageBed.toast.publishError": "Publish failed",
	"imageBed.toast.published": "✅ Published from cloud",
	"imageBed.toast.selectFirst": "Please select images first",
	"imageBed.toast.urlCopied": "✅ URL copied",
};
