/**
 * i18n dictionary: `mediaPage.*` (16 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"mediaPage.desc": "一个入口完成媒体浏览、筛选、扫描和图片外链发布；旧“图床”只作为已发布外链的管理与审计中心。",
	"mediaPage.eyebrow": "Media Workspace",
	"mediaPage.group.unassigned": "未分配存储",
	"mediaPage.stat.audio": "音频",
	"mediaPage.stat.image": "图片",
	"mediaPage.stat.video": "视频",
	"mediaPage.title": "媒体库",
	"mediaPage.workspace.all": "全部媒体",
	"mediaPage.workspace.allDesc": "从这里统一进入图片、视频、音频三个媒体工作流。",
	"mediaPage.workspace.audio": "音频库",
	"mediaPage.workspace.audioDesc": "集中浏览音频文件，支持播放、下载和按标签收藏整理。",
	"mediaPage.workspace.image": "图片工作区",
	"mediaPage.workspace.imageDesc": "上传、扫描、整理图片，并把已入库图片发布成可复制的外链。",
	"mediaPage.workspace.label": "Current Workspace",
	"mediaPage.workspace.video": "视频库",
	"mediaPage.workspace.videoDesc": "集中浏览视频文件，支持预览播放、下载和跳回源文件位置。",
};

export const en: Record<string, string> = {
	"mediaPage.desc": "Browse, filter, scan media, and publish image links from one place. The old Image Bed is now only the published link management and audit center.",
	"mediaPage.eyebrow": "Media Workspace",
	"mediaPage.group.unassigned": "Unassigned storage",
	"mediaPage.stat.audio": "Audio",
	"mediaPage.stat.image": "Images",
	"mediaPage.stat.video": "Videos",
	"mediaPage.title": "Media Library",
	"mediaPage.workspace.all": "All Media",
	"mediaPage.workspace.allDesc": "Unified entry point to the image, video, and audio media workflows.",
	"mediaPage.workspace.audio": "Audio Library",
	"mediaPage.workspace.audioDesc": "Browse audio files with playback, download, and tag-based favorites.",
	"mediaPage.workspace.image": "Image Workspace",
	"mediaPage.workspace.imageDesc": "Upload, scan, organize images, and publish them as copyable public links.",
	"mediaPage.workspace.label": "Current Workspace",
	"mediaPage.workspace.video": "Video Library",
	"mediaPage.workspace.videoDesc": "Browse video files in one place with preview, download, and jump to source.",
};
