/**
 * i18n dictionary: `monitoring.*` (7 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"monitoring.auto-refresh": "自动刷新",
	"monitoring.cpu": "CPU",
	"monitoring.disk": "磁盘",
	"monitoring.memory": "内存",
	"monitoring.network": "网络",
	"monitoring.title": "服务器监控",
	"monitoring.top-processes": "Top 进程",
};

export const en: Record<string, string> = {
	"monitoring.auto-refresh": "Auto Refresh",
	"monitoring.cpu": "CPU",
	"monitoring.disk": "Disk",
	"monitoring.memory": "Memory",
	"monitoring.network": "Network",
	"monitoring.title": "Server Monitoring",
	"monitoring.top-processes": "Top Processes",
};
