/**
 * i18n dictionary: `notFound.*` (3 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"notFound.description": "页面不存在或已被移除",
	"notFound.returnHome": "← 返回首页",
	"notFound.title": "404",
};

export const en: Record<string, string> = {
	"notFound.description": "Page not found or has been removed",
	"notFound.returnHome": "← Return Home",
	"notFound.title": "404",
};
