/**
 * i18n dictionary: `operationTasks.*` (17 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"operationTasks.action.applyFilter": "应用筛选",
	"operationTasks.action.refreshing": "刷新中...",
	"operationTasks.filter.all": "全部",
	"operationTasks.filter.attention": "需处理",
	"operationTasks.filter.completed": "已完成",
	"operationTasks.filter.failed": "失败",
	"operationTasks.filter.pending": "待处理",
	"operationTasks.filter.running": "运行中",
	"operationTasks.refreshFailed": "刷新任务中心失败",
	"operationTasks.sort.attention": "需处理优先",
	"operationTasks.sort.recent": "最新优先",
	"operationTasks.summary.failureGroup": "失败原因聚合",
	"operationTasks.summary.noFailures": "当前筛选结果暂无失败任务",
	"operationTasks.summary.noSources": "暂无来源分布",
	"operationTasks.summary.sourceGroup": "来源聚合",
	"operationTasks.summary.sourceGroupDesc": "按任务来源汇总当前筛选结果,优先显示失败/运行中/待处理数量。",
	"operationTasks.tasks.empty": "暂无匹配任务",
};

export const en: Record<string, string> = {
	"operationTasks.action.applyFilter": "Apply filter",
	"operationTasks.action.refreshing": "Refreshing...",
	"operationTasks.filter.all": "All",
	"operationTasks.filter.attention": "Needs attention",
	"operationTasks.filter.completed": "Completed",
	"operationTasks.filter.failed": "Failed",
	"operationTasks.filter.pending": "Pending",
	"operationTasks.filter.running": "Running",
	"operationTasks.refreshFailed": "Failed to refresh task center",
	"operationTasks.sort.attention": "Needs attention first",
	"operationTasks.sort.recent": "Newest first",
	"operationTasks.summary.failureGroup": "Failure aggregation",
	"operationTasks.summary.noFailures": "No failed tasks in the current filter",
	"operationTasks.summary.noSources": "No source distribution yet",
	"operationTasks.summary.sourceGroup": "Source aggregation",
	"operationTasks.summary.sourceGroupDesc": "Aggregated by source. Shows failed / running / pending counts first.",
	"operationTasks.tasks.empty": "No matching tasks",
};
