/**
 * i18n dictionary: `requestsPage.*` (18 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"requestsPage.ai.desc": "用于确认 AI 托管模式下的高风险工具调用，例如重启服务、修改配置、执行命令。",
	"requestsPage.ai.empty": "暂无 AI 助手待授权操作。AI 对话中触发高风险操作时会出现在这里。",
	"requestsPage.ai.scopeBadge": "只显示当前账号待处理授权",
	"requestsPage.ai.title": "AI 助手授权",
	"requestsPage.cmd.desc": "用于审批用户、运维成员或命令模板提交的 VPS 命令请求；也保留 AI 以命令请求形式发起的记录。",
	"requestsPage.cmd.empty": "暂无命令请求记录。",
	"requestsPage.cmd.scopeBadge": "批准后进入真实 SSH 执行流",
	"requestsPage.cmd.title": "用户命令审批",
	"requestsPage.desc": "AI 助手授权与用户命令审批",
	"requestsPage.eyebrow": "Workflow",
	"requestsPage.stat.aiPending": "AI 待授权",
	"requestsPage.stat.assistant": "助手命令",
	"requestsPage.stat.cmdPending": "命令待审批",
	"requestsPage.stat.completed": "已完成",
	"requestsPage.stat.user": "用户命令",
	"requestsPage.title": "审批中心",
	"requestsPage.workflowNote.desc": "AI 助手托管操作先授权再执行；用户/运维提交的命令请求走命令审批流。",
	"requestsPage.workflowNote.title": "当前支持两条审批链路",
	"requestsPage.cancel.title": "取消命令",

	"requestsPage.cancel.ariaLabel": "取消命令",

	"requestsPage.cancel.confirmTitle": "确认取消命令",

	"requestsPage.cancel.confirm": "确认取消",

	"requestsPage.cancel.pending": "取消中…",

	"requestsPage.cancel.errorFallback": "取消失败",

};

export const en: Record<string, string> = {
	"requestsPage.ai.desc": "Confirm high-risk tool calls under AI-hosted mode, e.g. service restarts, config changes, command execution.",
	"requestsPage.ai.empty": "No pending AI assistant authorizations. High-risk actions from AI chat will appear here.",
	"requestsPage.ai.scopeBadge": "Only pending authorizations for your account",
	"requestsPage.ai.title": "AI assistant authorization",
	"requestsPage.cmd.desc": "Approve VPS command requests from users, ops members, or command templates. Records from AI command requests are also kept here.",
	"requestsPage.cmd.empty": "No command requests yet.",
	"requestsPage.cmd.scopeBadge": "Approved requests enter the real SSH execution flow",
	"requestsPage.cmd.title": "User command approval",
	"requestsPage.desc": "AI assistant authorizations and user command approvals.",
	"requestsPage.eyebrow": "Workflow",
	"requestsPage.stat.aiPending": "AI pending",
	"requestsPage.stat.assistant": "Assistant commands",
	"requestsPage.stat.cmdPending": "Commands pending",
	"requestsPage.stat.completed": "Completed",
	"requestsPage.stat.user": "User commands",
	"requestsPage.title": "Approvals",
	"requestsPage.workflowNote.desc": "AI-hosted actions require authorization first; user/ops command requests go through the command approval flow.",
	"requestsPage.workflowNote.title": "Two approval flows are supported",
	"requestsPage.cancel.title": "Cancel command",

	"requestsPage.cancel.ariaLabel": "Cancel command",

	"requestsPage.cancel.confirmTitle": "Confirm cancellation",

	"requestsPage.cancel.confirm": "Confirm cancel",

	"requestsPage.cancel.pending": "Cancelling…",

	"requestsPage.cancel.errorFallback": "Cancellation failed",

};
