/**
 * i18n dictionary: `search.*` (12 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"search.category.action": "操作",
	"search.category.page": "页面",
	"search.category.public": "公开页面",
	"search.category.system": "系统",
	"search.category.tool": "工具",
	"search.dialog": "全局搜索",
	"search.input-label": "搜索页面和操作",
	"search.no-results": "未找到结果",
	"search.placeholder": "搜索页面、操作...",
	"search.shortcut-close": "ESC 关闭",
	"search.shortcut-confirm": "↵ 确认",
	"search.shortcut-select": "↑↓ 选择",
};

export const en: Record<string, string> = {
	"search.category.action": "Action",
	"search.category.page": "Page",
	"search.category.public": "Public page",
	"search.category.system": "System",
	"search.category.tool": "Tool",
	"search.dialog": "Global search",
	"search.input-label": "Search pages and actions",
	"search.no-results": "No results found",
	"search.placeholder": "Search pages, actions...",
	"search.shortcut-close": "ESC Close",
	"search.shortcut-confirm": "↵ Confirm",
	"search.shortcut-select": "↑↓ Select",
};
