/**
 * i18n dictionary: `serversPage.*` (14 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"serversPage.batchEmpty": "暂无可批量操作的 VPS。",
	"serversPage.desc": "聚焦 VPS 节点、SSH 密钥与直连网关维护；命令审批与投递记录统一进入审批中心。",
	"serversPage.link.audit": "查看审计日志",
	"serversPage.link.deploy": "去部署面板",
	"serversPage.link.request": "命令下发",
	"serversPage.noManage": "当前角色无节点纳管权限。",
	"serversPage.overview.aria": "VPS 状态总览",
	"serversPage.overview.empty": "暂无已纳管 VPS。使用上方“添加 VPS”录入 SSH 密钥、IP 与端口完成纳管。",
	"serversPage.stat.enabled": "启用节点",
	"serversPage.stat.storage": "已绑定存储",
	"serversPage.stat.total": "节点总数",
	"serversPage.statusPriority.desc": "默认先展示各 VPS 的启用状态、连接方式、密钥绑定、直连模式和待审批命令；添加 VPS、添加密钥、批量操作已收入口到快捷操作区。",
	"serversPage.statusPriority.title": "VPS 状态优先",
	"serversPage.title": "VPS 管理",
};

export const en: Record<string, string> = {
	"serversPage.batchEmpty": "No VPS available for batch operations.",
	"serversPage.desc": "Focus on VPS nodes, SSH keys, and direct gateway maintenance; command approvals and deliveries route through the approval center.",
	"serversPage.link.audit": "View audit log",
	"serversPage.link.deploy": "Open deployment panel",
	"serversPage.link.request": "Send command",
	"serversPage.noManage": "Your role doesn't have node management permission.",
	"serversPage.overview.aria": "VPS status overview",
	"serversPage.overview.empty": "No managed VPS yet. Use \"Add VPS\" above to register SSH key, IP, and port.",
	"serversPage.stat.enabled": "Enabled nodes",
	"serversPage.stat.storage": "Storage bound",
	"serversPage.stat.total": "Total nodes",
	"serversPage.statusPriority.desc": "Show each VPS's enabled state, connection, key binding, direct mode, and pending commands. Add VPS, add key, and batch actions are in the quick-action area.",
	"serversPage.statusPriority.title": "VPS status first",
	"serversPage.title": "VPS management",
};
