/**
 * i18n dictionary: `servers.*` (5 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"servers.add": "添加服务器",
	"servers.connect": "连接",
	"servers.offline": "离线",
	"servers.online": "在线",
	"servers.title": "服务器管理",
};

export const en: Record<string, string> = {
	"servers.add": "Add Server",
	"servers.connect": "Connect",
	"servers.offline": "Offline",
	"servers.online": "Online",
	"servers.title": "Server Management",
};
