/**
 * i18n dictionary: `serversPage.*` (14 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"serversPage.batchEmpty": "暂无可批量操作的 VPS。",
	"serversPage.desc": "聚焦 VPS 节点、SSH 密钥与直连网关维护；命令审批与投递记录统一进入审批中心。",
	"serversPage.link.audit": "查看审计日志",
	"serversPage.link.deploy": "去部署面板",
	"serversPage.link.request": "命令下发",
	"serversPage.noManage": "当前角色无节点纳管权限。",
	"serversPage.overview.aria": "VPS 状态总览",
	"serversPage.overview.empty": "暂无已纳管 VPS。使用上方“添加 VPS”录入 SSH 密钥、IP 与端口完成纳管。",
	"serversPage.stat.enabled": "启用节点",
	"serversPage.stat.storage": "已绑定存储",
	"serversPage.stat.total": "节点总数",
	"serversPage.statusPriority.desc": "默认先展示各 VPS 的启用状态、连接方式、密钥绑定、直连模式和待审批命令；添加 VPS、添加密钥、批量操作已收入口到快捷操作区。",
	"serversPage.statusPriority.title": "VPS 状态优先",
	"serversPage.title": "VPS 管理",
	"serversPage.command.title": "创建命令请求",

	"serversPage.command.titleLabel": "命令标题",

	"serversPage.command.titlePlaceholder": "例如：Restart nginx",

	"serversPage.command.bodyLabel": "命令内容",

	"serversPage.command.desc": "选择要执行命令的目标节点并填入命令内容。提交后进入命令审批流程。",

	"serversPage.command.selectAllEnabled": "全选启用节点",

	"serversPage.command.deselectAll": "取消全选",

	"serversPage.command.noAvailableNodes": "暂无可用启用节点；请先在 VPS 管理中启用至少一台服务器。",

	"serversPage.command.targetNodes": "目标节点",

	"serversPage.command.reasonLabel": "执行原因",

	"serversPage.create.title": "添加 VPS 节点",

	"serversPage.create.sshKey": "SSH 密钥",

	"serversPage.create.password": "密码",

	"serversPage.create.selectKey": "请选择已有密钥",

	"serversPage.create.passwordPlaceholder": "留空则使用密钥认证",

	"serversPage.create.namePlaceholder": "例如：慈云香港 VPS",

	"serversPage.create.descriptionPlaceholder": "可选说明",

	"serversPage.create.tagsPlaceholder": "ops, prod",

	"serversPage.create.storagePathDefault": "/root/drive",

	"serversPage.create.storagePathDesc": "VPS 上的默认存储目录",

	"serversPage.create.submit": "保存并校验连接",

	"serversPage.create.submitting": "校验中…",

	"serversPage.create.directGateway.title": "启用目标服务器直连",

	"serversPage.create.directGateway.note": "启用后对上传、下载、在线浏览/播放全局生效；之后也可在服务器管理面板切回中转并删除服务。",

	"serverOverviewDetails.sshInteractive": "SSH 交互连接",
	"serverOverviewDetails.verifiable": "可验证",
	"serverOverviewDetails.missingPermission": "缺少权限",
	"serverOverviewDetails.nodeDisabled": "节点停用",
	"serverOverviewDetails.sshInteractiveDetail": "从详情操作区打开 SSH 终端，确认凭据、网络和远端 shell 是否真实可用。",
	"serverOverviewDetails.enableNodeFirst": "先启用节点后再进行实时连接诊断。",
	"serverOverviewDetails.sftpManagement": "SFTP / 文件管理",
	"serverOverviewDetails.bound": "已绑定",
	"serverOverviewDetails.unbound": "未绑定",
	"serverOverviewDetails.sftpDetailPrefix": "文件入口将使用 ",
	"serverOverviewDetails.sftpDetailSuffix": "。",
	"serverOverviewDetails.sftpUnboundDetail": "未绑定存储节点时，文件浏览、媒体索引和直连文件代理都缺少真实目录边界。",
	"serverOverviewDetails.directGateway": "Direct Gateway",
	"serverOverviewDetails.configured": "已配置",
	"serverOverviewDetails.websiteRelay": "网站中转",
	"serverOverviewDetails.commandApprovalQueue": "命令审批队列",
	"serverOverviewDetails.pendingCountSuffix": " 条待处理",
	"serverOverviewDetails.noPending": "无待审批",
	"serverOverviewDetails.pendingDetail": "先处理审批中心里的待审批命令，避免诊断结果被排队任务遮蔽。",
	"serverOverviewDetails.noPendingDetail": "没有待审批命令阻塞当前节点操作。",
	"serverOverviewDetails.connectionType": "连接方式",
	"serverOverviewDetails.username": "登录账号",
	"serverOverviewDetails.address": "地址",
	"serverOverviewDetails.nodeStatus": "节点状态",
	"serverOverviewDetails.notConfigured": "未配置",
	"serverOverviewDetails.relatedStorage": "关联存储",
	"serverOverviewDetails.directMode": "直连模式",
	"serverOverviewDetails.totalCommandTargets": "累计命令目标",
	"serverOverviewDetails.connectionSummary": "连接摘要",
	"serverOverviewDetails.diagnosing": "探测中...",
	"serverOverviewDetails.runRealtimeDiagnostics": "运行实时探测",
	"serverOverviewDetails.assistant": "助手",
	"serverOverviewDetails.user": "用户",
	"serverOverviewDetails.recommendation": "建议",
	"serverOverviewDetails.reference": "参考",
	"serverOverviewDetails.vpsDetails": "VPS 详情",

	"serverOverviewDetails.directGatewayRepairAdvice": "Direct Gateway 修复建议",

	"serverOverviewCard.websiteRelay": "网站中转",
	"serverOverviewCard.disabled": "停用",
	"serverOverviewCard.disabledDescription": "节点已停用，不会接收新的 SSH、文件或直连操作。",
	"serverOverviewCard.checking": "检测中",
	"serverOverviewCard.checkingDescription": "正在通过 /api/servers/monitor 实时探测，请稍候。",
	"serverOverviewCard.offline": "离线",
	"serverOverviewCard.enabledPendingProbe": "启用 · 待探测",
	"serverOverviewCard.enabledPendingProbeDescription": "该节点已允许接收操作，但列表状态未代表 SSH/SFTP/直连实时在线；展开详情可运行实时探测。",
	"serverOverviewCard.realtimeProbeFailed": "实时探测失败",
	"serverOverviewCard.connection": "连接",
	"serverOverviewCard.key": "密钥",
	"serverOverviewCard.direct": "直连",
	"serverOverviewCard.notConfigured": "未配置",
	"serverOverviewCard.collapseDetails": "收起详情",
	"serverOverviewCard.viewDetails": "查看详情",
	"serverOverviewCard.pendingApproval": "待审批",
	"serverOverviewCard.itemsCount": " 条",

	// server-card-actions (R15)
	"serverCardActions.sshTerminalButton": "SSH 终端",
	"serverCardActions.sshTerminalAria": "打开 {name} SSH 终端",
	"serverCardActions.directGateway.formAria": "目标服务器直连网关控制",
	"serverCardActions.directGateway.statusPrefix": "直连状态：{status}",
	"serverCardActions.directGateway.relayHint": "当前上传、下载、在线浏览默认走网站中转。",
	"serverCardActions.directGateway.enabledTitle": "直连服务已声明启用。",
	"serverCardActions.directGateway.enabledDetail": "若文件预览/下载异常，请先确认目标 VPS 上 Direct Gateway 进程仍在监听 {port}，并检查防火墙是否放行该端口；切回网站中转会先尝试卸载远端服务，成功后再更新数据库状态。",
	"serverCardActions.directGateway.enabledDetailPortFallback": "配置端口",
	"serverCardActions.directGateway.disabledTitle": "启用前检查：VPS 必须绑定 SFTP 存储节点且不是本机地址。",
	"serverCardActions.directGateway.disabledDetail": "点击启用会通过 SSH 安装目标服务器 Direct Gateway；如果远端安装失败，页面会保留网站中转并显示错误，不会把直连标记成成功。",
	"serverCardActions.directGateway.pendingDisable": "删除服务中...",
	"serverCardActions.directGateway.pendingEnable": "安装服务中...",
	"serverCardActions.directGateway.disableLabel": "切回网站中转并删除直连服务",
	"serverCardActions.directGateway.enableLabel": "启用目标直连",
	"serverCardActions.edit.toggleShow": "编辑节点",
	"serverCardActions.edit.toggleHide": "收起编辑",
	"serverCardActions.edit.formAria": "编辑 VPS 节点",
	"serverCardActions.edit.name": "节点名称",
	"serverCardActions.edit.host": "IP / 域名",
	"serverCardActions.edit.port": "SSH 端口",
	"serverCardActions.edit.username": "用户名",
	"serverCardActions.edit.password": "新密码（留空保持不变）",
	"serverCardActions.edit.description": "描述",
	"serverCardActions.edit.tags": "标签",
	"serverCardActions.edit.pending": "校验中...",
	"serverCardActions.edit.submit": "保存并校验连接",
	"serverCardActions.toggle.pending": "处理中...",
	"serverCardActions.toggle.enable": "启用节点",
	"serverCardActions.toggle.disable": "停用节点",
	"serverCardActions.delete.relatedStorageHint": "该 VPS 关联了 {count} 个存储节点，删除后存储节点将失去 VPS 绑定",
	"serverCardActions.delete.postConfirmHint": "删除成功后节点会从 VPS 列表移除，并同步清理关联存储/直连状态；请输入节点名称完成确认。",
	"serverCardActions.delete.pending": "删除中...",
	"serverCardActions.delete.confirm": "删除节点",
	"serverCardActions.delete.pendingLookup": "查询中...",
	"serverCardActions.delete.cancel": "取消",
};

export const en: Record<string, string> = {
	"serversPage.batchEmpty": "No VPS available for batch operations.",
	"serversPage.desc": "Focus on VPS nodes, SSH keys, and direct gateway maintenance; command approvals and deliveries route through the approval center.",
	"serversPage.link.audit": "View audit log",
	"serversPage.link.deploy": "Open deployment panel",
	"serversPage.link.request": "Send command",
	"serversPage.noManage": "Your role doesn't have node management permission.",
	"serversPage.overview.aria": "VPS status overview",
	"serversPage.overview.empty": "No managed VPS yet. Use \"Add VPS\" above to register SSH key, IP, and port.",
	"serversPage.stat.enabled": "Enabled nodes",
	"serversPage.stat.storage": "Storage bound",
	"serversPage.stat.total": "Total nodes",
	"serversPage.statusPriority.desc": "Show each VPS's enabled state, connection, key binding, direct mode, and pending commands. Add VPS, add key, and batch actions are in the quick-action area.",
	"serversPage.statusPriority.title": "VPS status first",
	"serversPage.title": "VPS management",
	"serversPage.command.title": "Create command request",

	"serversPage.command.titleLabel": "Command title",

	"serversPage.command.titlePlaceholder": "e.g. Restart nginx",

	"serversPage.command.bodyLabel": "Command body",

	"serversPage.command.desc": "Pick target VPS nodes and provide the command body. Submission enters the command approval flow.",

	"serversPage.command.selectAllEnabled": "Select all enabled",

	"serversPage.command.deselectAll": "Deselect all",

	"serversPage.command.noAvailableNodes": "No enabled VPS nodes; please enable at least one in VPS management first.",

	"serversPage.command.targetNodes": "Target nodes",

	"serversPage.command.reasonLabel": "Reason for execution",

	"serversPage.create.title": "Add VPS node",

	"serversPage.create.sshKey": "SSH key",

	"serversPage.create.password": "Password",

	"serversPage.create.selectKey": "Select an existing key",

	"serversPage.create.passwordPlaceholder": "Leave blank to use SSH key auth",

	"serversPage.create.namePlaceholder": "e.g. Hong Kong VPS",

	"serversPage.create.descriptionPlaceholder": "Optional notes",

	"serversPage.create.tagsPlaceholder": "ops, prod",

	"serversPage.create.storagePathDefault": "/root/drive",

	"serversPage.create.storagePathDesc": "Default storage directory on the VPS",

	"serversPage.create.submit": "Save and verify connection",

	"serversPage.create.submitting": "Verifying…",

	"serversPage.create.directGateway.title": "Enable target server direct access",

	"serversPage.create.directGateway.note": "Once enabled, upload, download and online viewing/streaming will use direct access globally. You can switch back to relay later from the server management panel.",

	"serverOverviewDetails.sshInteractive": "SSH interactive connection",
	"serverOverviewDetails.verifiable": "Verifiable",
	"serverOverviewDetails.missingPermission": "Missing permission",
	"serverOverviewDetails.nodeDisabled": "Node disabled",
	"serverOverviewDetails.sshInteractiveDetail": "Open SSH terminal from the actions area to verify credentials, network, and remote shell.",
	"serverOverviewDetails.enableNodeFirst": "Enable the node before running realtime connection diagnostics.",
	"serverOverviewDetails.sftpManagement": "SFTP / File management",
	"serverOverviewDetails.bound": "Bound",
	"serverOverviewDetails.unbound": "Unbound",
	"serverOverviewDetails.sftpDetailPrefix": "File entry will use ",
	"serverOverviewDetails.sftpDetailSuffix": ".",
	"serverOverviewDetails.sftpUnboundDetail": "Without a storage node bound, file browser, media index, and direct file proxy lack a real directory boundary.",
	"serverOverviewDetails.directGateway": "Direct Gateway",
	"serverOverviewDetails.configured": "Configured",
	"serverOverviewDetails.websiteRelay": "Website relay",
	"serverOverviewDetails.commandApprovalQueue": "Command approval queue",
	"serverOverviewDetails.pendingCountSuffix": " pending",
	"serverOverviewDetails.noPending": "No pending",
	"serverOverviewDetails.pendingDetail": "Handle pending commands in the approval center first to avoid diagnostic results being obscured by queued tasks.",
	"serverOverviewDetails.noPendingDetail": "No pending commands are blocking operations on this node.",
	"serverOverviewDetails.connectionType": "Connection type",
	"serverOverviewDetails.username": "Username",
	"serverOverviewDetails.address": "Address",
	"serverOverviewDetails.nodeStatus": "Node status",
	"serverOverviewDetails.notConfigured": "Not configured",
	"serverOverviewDetails.relatedStorage": "Related storage",
	"serverOverviewDetails.directMode": "Direct mode",
	"serverOverviewDetails.totalCommandTargets": "Total command targets",
	"serverOverviewDetails.connectionSummary": "Connection summary",
	"serverOverviewDetails.diagnosing": "Diagnosing…",
	"serverOverviewDetails.runRealtimeDiagnostics": "Run realtime diagnostics",
	"serverOverviewDetails.assistant": "Assistant",
	"serverOverviewDetails.user": "User",
	"serverOverviewDetails.recommendation": "Recommendation",
	"serverOverviewDetails.reference": "Reference",
	"serverOverviewDetails.vpsDetails": "VPS details",

	"serverOverviewDetails.directGatewayRepairAdvice": "Direct Gateway repair advice",

	"serverOverviewCard.websiteRelay": "Website relay",
	"serverOverviewCard.disabled": "Disabled",
	"serverOverviewCard.disabledDescription": "Node is disabled and will not accept new SSH, file, or direct operations.",
	"serverOverviewCard.checking": "Checking",
	"serverOverviewCard.checkingDescription": "Running realtime probe via /api/servers/monitor, please wait.",
	"serverOverviewCard.offline": "Offline",
	"serverOverviewCard.enabledPendingProbe": "Enabled · awaiting probe",
	"serverOverviewCard.enabledPendingProbeDescription": "Node accepts operations, but list status does not reflect realtime SSH/SFTP/direct connectivity. Expand details to run a realtime probe.",
	"serverOverviewCard.realtimeProbeFailed": "Realtime probe failed",
	"serverOverviewCard.connection": "Connection",
	"serverOverviewCard.key": "Key",
	"serverOverviewCard.direct": "Direct",
	"serverOverviewCard.notConfigured": "Not configured",
	"serverOverviewCard.collapseDetails": "Collapse details",
	"serverOverviewCard.viewDetails": "View details",
	"serverOverviewCard.pendingApproval": "Pending approval",
	"serverOverviewCard.itemsCount": " items",

	// server-card-actions (R15)
	"serverCardActions.sshTerminalButton": "SSH terminal",
	"serverCardActions.sshTerminalAria": "Open {name} SSH terminal",
	"serverCardActions.directGateway.formAria": "Target server direct gateway control",
	"serverCardActions.directGateway.statusPrefix": "Direct status: {status}",
	"serverCardActions.directGateway.relayHint": "Uploads, downloads and online browsing currently go through website relay.",
	"serverCardActions.directGateway.enabledTitle": "Direct service marked enabled.",
	"serverCardActions.directGateway.enabledDetail": "If file preview/download fails, verify the Direct Gateway process on the target VPS is still listening on {port} and the firewall allows the port. Switching back to relay uninstalls the remote service first, then updates the DB status.",
	"serverCardActions.directGateway.enabledDetailPortFallback": "the configured port",
	"serverCardActions.directGateway.disabledTitle": "Before enabling: the VPS must be bound to an SFTP storage node and must not be localhost.",
	"serverCardActions.directGateway.disabledDetail": "Enabling installs Direct Gateway on the target server via SSH. If the remote install fails, the page keeps website relay and shows an error — direct access will not be marked successful.",
	"serverCardActions.directGateway.pendingDisable": "Removing service…",
	"serverCardActions.directGateway.pendingEnable": "Installing service…",
	"serverCardActions.directGateway.disableLabel": "Switch back to relay and remove direct service",
	"serverCardActions.directGateway.enableLabel": "Enable target direct access",
	"serverCardActions.edit.toggleShow": "Edit node",
	"serverCardActions.edit.toggleHide": "Collapse edit",
	"serverCardActions.edit.formAria": "Edit VPS node",
	"serverCardActions.edit.name": "Node name",
	"serverCardActions.edit.host": "IP / domain",
	"serverCardActions.edit.port": "SSH port",
	"serverCardActions.edit.username": "Username",
	"serverCardActions.edit.password": "New password (leave empty to keep current)",
	"serverCardActions.edit.description": "Description",
	"serverCardActions.edit.tags": "Tags",
	"serverCardActions.edit.pending": "Validating…",
	"serverCardActions.edit.submit": "Save and validate connection",
	"serverCardActions.toggle.pending": "Processing…",
	"serverCardActions.toggle.enable": "Enable node",
	"serverCardActions.toggle.disable": "Disable node",
	"serverCardActions.delete.relatedStorageHint": "This VPS is bound to {count} storage node(s); removing the VPS detaches those storage nodes.",
	"serverCardActions.delete.postConfirmHint": "After successful deletion the node is removed from the VPS list and related storage/direct state is cleaned up. Type the node name to confirm.",
	"serverCardActions.delete.pending": "Deleting…",
	"serverCardActions.delete.confirm": "Delete node",
	"serverCardActions.delete.pendingLookup": "Checking…",
	"serverCardActions.delete.cancel": "Cancel",
};
