/**
 * i18n dictionary: `serversPage.*` (14 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"serversPage.batchEmpty": "暂无可批量操作的 VPS。",
	"serversPage.desc": "聚焦 VPS 节点、SSH 密钥与直连网关维护；命令审批与投递记录统一进入审批中心。",
	"serversPage.link.audit": "查看审计日志",
	"serversPage.link.deploy": "去部署面板",
	"serversPage.link.request": "命令下发",
	"serversPage.noManage": "当前角色无节点纳管权限。",
	"serversPage.overview.aria": "VPS 状态总览",
	"serversPage.overview.empty": "暂无已纳管 VPS。使用上方“添加 VPS”录入 SSH 密钥、IP 与端口完成纳管。",
	"serversPage.stat.enabled": "启用节点",
	"serversPage.stat.storage": "已绑定存储",
	"serversPage.stat.total": "节点总数",
	"serversPage.statusPriority.desc": "默认先展示各 VPS 的启用状态、连接方式、密钥绑定、直连模式和待审批命令；添加 VPS、添加密钥、批量操作已收入口到快捷操作区。",
	"serversPage.statusPriority.title": "VPS 状态优先",
	"serversPage.title": "VPS 管理",
	"serversPage.command.title": "创建命令请求",

	"serversPage.command.titleLabel": "命令标题",

	"serversPage.command.titlePlaceholder": "例如：Restart nginx",

	"serversPage.command.bodyLabel": "命令内容",

	"serversPage.command.desc": "选择要执行命令的目标节点并填入命令内容。提交后进入命令审批流程。",

	"serversPage.command.selectAllEnabled": "全选启用节点",

	"serversPage.command.deselectAll": "取消全选",

	"serversPage.command.noAvailableNodes": "暂无可用启用节点；请先在 VPS 管理中启用至少一台服务器。",

	"serversPage.command.targetNodes": "目标节点",

	"serversPage.command.reasonLabel": "执行原因",

	"serversPage.create.title": "添加 VPS 节点",

	"serversPage.create.sshKey": "SSH 密钥",

	"serversPage.create.password": "密码",

	"serversPage.create.selectKey": "请选择已有密钥",

	"serversPage.create.passwordPlaceholder": "留空则使用密钥认证",

	"serversPage.create.namePlaceholder": "例如：慈云香港 VPS",

	"serversPage.create.descriptionPlaceholder": "可选说明",

	"serversPage.create.tagsPlaceholder": "ops, prod",

	"serversPage.create.storagePathDefault": "/root/drive",

	"serversPage.create.storagePathDesc": "VPS 上的默认存储目录",

	"serversPage.create.submit": "保存并校验连接",

	"serversPage.create.submitting": "校验中…",

	"serversPage.create.directGateway.title": "启用目标服务器直连",

	"serversPage.create.directGateway.note": "启用后对上传、下载、在线浏览/播放全局生效；之后也可在服务器管理面板切回中转并删除服务。",

	"serverOverviewDetails.sshInteractive": "SSH 交互连接",
	"serverOverviewDetails.verifiable": "可验证",
	"serverOverviewDetails.missingPermission": "缺少权限",
	"serverOverviewDetails.nodeDisabled": "节点停用",
	"serverOverviewDetails.sshInteractiveDetail": "从详情操作区打开 SSH 终端，确认凭据、网络和远端 shell 是否真实可用。",
	"serverOverviewDetails.enableNodeFirst": "先启用节点后再进行实时连接诊断。",
	"serverOverviewDetails.sftpManagement": "SFTP / 文件管理",
	"serverOverviewDetails.bound": "已绑定",
	"serverOverviewDetails.unbound": "未绑定",
	"serverOverviewDetails.sftpDetailPrefix": "文件入口将使用 ",
	"serverOverviewDetails.sftpDetailSuffix": "。",
	"serverOverviewDetails.sftpUnboundDetail": "未绑定存储节点时，文件浏览、媒体索引和直连文件代理都缺少真实目录边界。",
	"serverOverviewDetails.directGateway": "Direct Gateway",
	"serverOverviewDetails.configured": "已配置",
	"serverOverviewDetails.websiteRelay": "网站中转",
	"serverOverviewDetails.commandApprovalQueue": "命令审批队列",
	"serverOverviewDetails.pendingCountSuffix": " 条待处理",
	"serverOverviewDetails.noPending": "无待审批",
	"serverOverviewDetails.pendingDetail": "先处理审批中心里的待审批命令，避免诊断结果被排队任务遮蔽。",
	"serverOverviewDetails.noPendingDetail": "没有待审批命令阻塞当前节点操作。",
	"serverOverviewDetails.connectionType": "连接方式",
	"serverOverviewDetails.username": "登录账号",
	"serverOverviewDetails.address": "地址",
	"serverOverviewDetails.nodeStatus": "节点状态",
	"serverOverviewDetails.notConfigured": "未配置",
	"serverOverviewDetails.relatedStorage": "关联存储",
	"serverOverviewDetails.directMode": "直连模式",
	"serverOverviewDetails.totalCommandTargets": "累计命令目标",
	"serverOverviewDetails.connectionSummary": "连接摘要",
	"serverOverviewDetails.diagnosing": "探测中...",
	"serverOverviewDetails.runRealtimeDiagnostics": "运行实时探测",
	"serverOverviewDetails.assistant": "助手",
	"serverOverviewDetails.user": "用户",
	"serverOverviewDetails.recommendation": "建议",
	"serverOverviewDetails.reference": "参考",
	"serverOverviewDetails.vpsDetails": "VPS 详情",

	"serverOverviewDetails.directGatewayRepairAdvice": "Direct Gateway 修复建议",
};

export const en: Record<string, string> = {
	"serversPage.batchEmpty": "No VPS available for batch operations.",
	"serversPage.desc": "Focus on VPS nodes, SSH keys, and direct gateway maintenance; command approvals and deliveries route through the approval center.",
	"serversPage.link.audit": "View audit log",
	"serversPage.link.deploy": "Open deployment panel",
	"serversPage.link.request": "Send command",
	"serversPage.noManage": "Your role doesn't have node management permission.",
	"serversPage.overview.aria": "VPS status overview",
	"serversPage.overview.empty": "No managed VPS yet. Use \"Add VPS\" above to register SSH key, IP, and port.",
	"serversPage.stat.enabled": "Enabled nodes",
	"serversPage.stat.storage": "Storage bound",
	"serversPage.stat.total": "Total nodes",
	"serversPage.statusPriority.desc": "Show each VPS's enabled state, connection, key binding, direct mode, and pending commands. Add VPS, add key, and batch actions are in the quick-action area.",
	"serversPage.statusPriority.title": "VPS status first",
	"serversPage.title": "VPS management",
	"serversPage.command.title": "Create command request",

	"serversPage.command.titleLabel": "Command title",

	"serversPage.command.titlePlaceholder": "e.g. Restart nginx",

	"serversPage.command.bodyLabel": "Command body",

	"serversPage.command.desc": "Pick target VPS nodes and provide the command body. Submission enters the command approval flow.",

	"serversPage.command.selectAllEnabled": "Select all enabled",

	"serversPage.command.deselectAll": "Deselect all",

	"serversPage.command.noAvailableNodes": "No enabled VPS nodes; please enable at least one in VPS management first.",

	"serversPage.command.targetNodes": "Target nodes",

	"serversPage.command.reasonLabel": "Reason for execution",

	"serversPage.create.title": "Add VPS node",

	"serversPage.create.sshKey": "SSH key",

	"serversPage.create.password": "Password",

	"serversPage.create.selectKey": "Select an existing key",

	"serversPage.create.passwordPlaceholder": "Leave blank to use SSH key auth",

	"serversPage.create.namePlaceholder": "e.g. Hong Kong VPS",

	"serversPage.create.descriptionPlaceholder": "Optional notes",

	"serversPage.create.tagsPlaceholder": "ops, prod",

	"serversPage.create.storagePathDefault": "/root/drive",

	"serversPage.create.storagePathDesc": "Default storage directory on the VPS",

	"serversPage.create.submit": "Save and verify connection",

	"serversPage.create.submitting": "Verifying…",

	"serversPage.create.directGateway.title": "Enable target server direct access",

	"serversPage.create.directGateway.note": "Once enabled, upload, download and online viewing/streaming will use direct access globally. You can switch back to relay later from the server management panel.",

	"serverOverviewDetails.sshInteractive": "SSH interactive connection",
	"serverOverviewDetails.verifiable": "Verifiable",
	"serverOverviewDetails.missingPermission": "Missing permission",
	"serverOverviewDetails.nodeDisabled": "Node disabled",
	"serverOverviewDetails.sshInteractiveDetail": "Open SSH terminal from the actions area to verify credentials, network, and remote shell.",
	"serverOverviewDetails.enableNodeFirst": "Enable the node before running realtime connection diagnostics.",
	"serverOverviewDetails.sftpManagement": "SFTP / File management",
	"serverOverviewDetails.bound": "Bound",
	"serverOverviewDetails.unbound": "Unbound",
	"serverOverviewDetails.sftpDetailPrefix": "File entry will use ",
	"serverOverviewDetails.sftpDetailSuffix": ".",
	"serverOverviewDetails.sftpUnboundDetail": "Without a storage node bound, file browser, media index, and direct file proxy lack a real directory boundary.",
	"serverOverviewDetails.directGateway": "Direct Gateway",
	"serverOverviewDetails.configured": "Configured",
	"serverOverviewDetails.websiteRelay": "Website relay",
	"serverOverviewDetails.commandApprovalQueue": "Command approval queue",
	"serverOverviewDetails.pendingCountSuffix": " pending",
	"serverOverviewDetails.noPending": "No pending",
	"serverOverviewDetails.pendingDetail": "Handle pending commands in the approval center first to avoid diagnostic results being obscured by queued tasks.",
	"serverOverviewDetails.noPendingDetail": "No pending commands are blocking operations on this node.",
	"serverOverviewDetails.connectionType": "Connection type",
	"serverOverviewDetails.username": "Username",
	"serverOverviewDetails.address": "Address",
	"serverOverviewDetails.nodeStatus": "Node status",
	"serverOverviewDetails.notConfigured": "Not configured",
	"serverOverviewDetails.relatedStorage": "Related storage",
	"serverOverviewDetails.directMode": "Direct mode",
	"serverOverviewDetails.totalCommandTargets": "Total command targets",
	"serverOverviewDetails.connectionSummary": "Connection summary",
	"serverOverviewDetails.diagnosing": "Diagnosing…",
	"serverOverviewDetails.runRealtimeDiagnostics": "Run realtime diagnostics",
	"serverOverviewDetails.assistant": "Assistant",
	"serverOverviewDetails.user": "User",
	"serverOverviewDetails.recommendation": "Recommendation",
	"serverOverviewDetails.reference": "Reference",
	"serverOverviewDetails.vpsDetails": "VPS details",

	"serverOverviewDetails.directGatewayRepairAdvice": "Direct Gateway repair advice",
};
