/**
 * i18n dictionary: `servers.*` + `serversPage.*` (33 keys).
 *
 * `servers.*` covers the small status/badge surface (add/connect/online/offline/title).
 * `serversPage.create.*` covers the "Add VPS node" dialog form fields and direct-gateway copy.
 * `serversPage.delete.*` (R10I micro-task) covers the destructive-delete confirmation dialog
 * (alertdialog title + typed-name input label) used by `ServerCardActions`.
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"servers.add": "添加服务器",
	"servers.connect": "连接",
	"servers.offline": "离线",
	"servers.online": "在线",
	"servers.title": "服务器管理",
	"serversPage.create.title": "添加 VPS 节点",
	"serversPage.create.desc": "录入 SSH 密钥、IP 与端口完成纳管",
	"serversPage.create.connectionType": "连接方式",
	"serversPage.create.connectionType.SSH_KEY": "SSH 密钥",
	"serversPage.create.connectionType.PASSWORD": "密码",
	"serversPage.create.sshKey": "SSH 密钥",
	"serversPage.create.sshKeyPlaceholder": "选择密钥",
	"serversPage.create.username": "用户名",
	"serversPage.create.password": "密码",
	"serversPage.create.passwordPlaceholder": "留空，不使用默认密码",
	"serversPage.create.passwordHint": "密码不会预填；请手动输入目标 VPS 当前 SSH 密码。",
	"serversPage.create.name": "节点名称",
	"serversPage.create.namePlaceholder": "例如 prod-1",
	"serversPage.create.description": "描述",
	"serversPage.create.descriptionPlaceholder": "可选",
	"serversPage.create.host": "IP / 主机名",
	"serversPage.create.port": "端口",
	"serversPage.create.storagePath": "存储路径",
	"serversPage.create.storagePathDesc": "VPS 上的文件存储目录，用于云盘和媒体库。默认",
	"serversPage.create.directGateway.title": "启用目标服务器直连",
	"serversPage.create.directGateway.desc": "默认使用网站服务器中转；勾选后会通过 SSH 安装 VControlHub Direct Gateway 微服务。",
	"serversPage.create.directGateway.note": "启用后对上传、下载、在线浏览/播放全局生效；之后也可在服务器管理面板切回中转并删除服务。",
	"serversPage.create.tags": "标签",
	"serversPage.create.tagsPlaceholder": "逗号分隔，例如 prod,web",
	"serversPage.create.submit": "添加节点",
	"serversPage.create.submitting": "添加中…",
	"serversPage.delete.confirmTitle": "确认删除「{name}」？",
	"serversPage.delete.confirmNameInput": "输入 VPS 名称「{name}」确认删除",

};

export const en: Record<string, string> = {
	"servers.add": "Add Server",
	"servers.connect": "Connect",
	"servers.offline": "Offline",
	"servers.online": "Online",
	"servers.title": "Server Management",
	"serversPage.create.title": "Add VPS node",
	"serversPage.create.desc": "Provide SSH key, IP and port to onboard the node",
	"serversPage.create.connectionType": "Connection type",
	"serversPage.create.connectionType.SSH_KEY": "SSH key",
	"serversPage.create.connectionType.PASSWORD": "Password",
	"serversPage.create.sshKey": "SSH key",
	"serversPage.create.sshKeyPlaceholder": "Select a key",
	"serversPage.create.username": "Username",
	"serversPage.create.password": "Password",
	"serversPage.create.passwordPlaceholder": "Leave empty to skip default password",
	"serversPage.create.passwordHint": "Password is never pre-filled; enter the current SSH password of the target VPS manually.",
	"serversPage.create.name": "Node name",
	"serversPage.create.namePlaceholder": "e.g. prod-1",
	"serversPage.create.description": "Description",
	"serversPage.create.descriptionPlaceholder": "Optional",
	"serversPage.create.host": "IP / hostname",
	"serversPage.create.port": "Port",
	"serversPage.create.storagePath": "Storage path",
	"serversPage.create.storagePathDesc": "File storage directory on the VPS, used by cloud drive and media library. Default",
	"serversPage.create.directGateway.title": "Enable target server direct access",
	"serversPage.create.directGateway.desc": "By default the web server relays traffic; when enabled, VControlHub Direct Gateway microservice will be installed via SSH.",
	"serversPage.create.directGateway.note": "Once enabled, upload, download and online viewing/streaming will use direct access globally. You can switch back to relay later from the server management panel.",
	"serversPage.create.tags": "Tags",
	"serversPage.create.tagsPlaceholder": "Comma separated, e.g. prod,web",
	"serversPage.create.submit": "Add node",
	"serversPage.create.submitting": "Adding…",
	"serversPage.delete.confirmTitle": "Delete \"{name}\"?",
	"serversPage.delete.confirmNameInput": "Type VPS name \"{name}\" to confirm delete",

};
