/**
 * i18n dictionary: `shares.*` (13 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"shares.accessCountPrefix": "访问 ",
	"shares.accessCountSuffix": " 次",
	"shares.createdAt": "创建",
	"shares.desc": "管理从文件管理中真实文件生成的可撤销、可过期分享链接；数据库仅保存 token 哈希。",
	"shares.empty": "暂无分享链接",
	"shares.expiresAt": "到期",
	"shares.neverExpires": "永不过期",
	"shares.noPermission": "你没有分享链接查看权限。",
	"shares.records": "分享记录",
	"shares.status.active": "有效",
	"shares.status.expired": "已过期",
	"shares.status.revoked": "已撤销",
	"shares.title": "文件分享链接",
};

export const en: Record<string, string> = {
	"shares.accessCountPrefix": "Accessed ",
	"shares.accessCountSuffix": " times",
	"shares.createdAt": "Created",
	"shares.desc": "Manage revocable, expiring share links generated from real files in the file manager. The database stores only token hashes.",
	"shares.empty": "No share links yet",
	"shares.expiresAt": "Expires",
	"shares.neverExpires": "Never expires",
	"shares.noPermission": "You don't have permission to view share links.",
	"shares.records": "Share records",
	"shares.status.active": "Active",
	"shares.status.expired": "Expired",
	"shares.status.revoked": "Revoked",
	"shares.title": "File share links",
};
