/**
 * i18n dictionary: `statusPage.*`.
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"statusPage.desc": "公开安全摘要，不展示主机名、端口、连接串或内部凭据。",
	"statusPage.overallLabel": "总体：",
	"statusPage.title": "服务状态",
	"statusPage.updatedAt": "更新时间：",
	"statusPage.health.healthy": "正常",
	"statusPage.health.warning": "警告",
	"statusPage.health.degraded": "异常",
	"statusPage.health.critical": "异常",
	"statusPage.public.detailsHint": "登录后可查看分项健康检查与 90 天可用率；匿名访问仅显示总体状态。",
	"statusPage.uptime.title": "历史可用率（90 天）",
	"statusPage.uptime.desc": "显示过去 90 天的服务器 uptime 情况",
	"statusPage.uptime.defaultServerName": "服务器",
	"statusPage.uptime.slaLabel": "SLA：",
};

export const en: Record<string, string> = {
	"statusPage.desc": "Public safety summary. Hostnames, ports, connection strings, and internal credentials are not exposed.",
	"statusPage.overallLabel": "Overall: ",
	"statusPage.title": "Service Status",
	"statusPage.updatedAt": "Updated at: ",
	"statusPage.health.healthy": "Healthy",
	"statusPage.health.warning": "Warning",
	"statusPage.health.degraded": "Degraded",
	"statusPage.health.critical": "Critical",
	"statusPage.public.detailsHint": "Sign in to view component health checks and 90-day uptime; anonymous visitors only see overall status.",
	"statusPage.uptime.title": "Historical uptime (90 days)",
	"statusPage.uptime.desc": "Shows server uptime over the past 90 days.",
	"statusPage.uptime.defaultServerName": "Server",
	"statusPage.uptime.slaLabel": "SLA: ",
};
