/**
 * i18n dictionary: `statusPage.*` (4 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"statusPage.desc": "公开安全摘要，不展示主机名、端口、连接串或内部凭据。",
	"statusPage.overallLabel": "总体：",
	"statusPage.title": "服务状态",
	"statusPage.updatedAt": "更新时间：",
};

export const en: Record<string, string> = {
	"statusPage.desc": "Public safety summary. Hostnames, ports, connection strings, and internal credentials are not exposed.",
	"statusPage.overallLabel": "Overall: ",
	"statusPage.title": "Service Status",
	"statusPage.updatedAt": "Updated at: ",
};
