/**
 * i18n dictionary: `statusPage.*`.
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"statusPage.desc": "公开安全摘要，不展示主机名、端口、连接串或内部凭据。",
	"statusPage.overallLabel": "总体：",
	"statusPage.title": "服务状态",
	"statusPage.updatedAt": "更新时间：",
	"statusPage.health.healthy": "正常",
	"statusPage.health.warning": "警告",
	"statusPage.health.degraded": "异常",
	"statusPage.health.critical": "异常",
	"statusPage.public.detailsHint": "匿名访客可查看总体状态与 90 天历史可用率热力图（仅节点显示名，无主机/端口）。登录后可查看分项健康检查详情。",
	"statusPage.uptime.title": "历史可用率（90 天）",
	"statusPage.uptime.desc": "显示过去 90 天的服务器 uptime 情况",
	"statusPage.uptime.defaultServerName": "服务器",
	"statusPage.uptime.slaLabel": "SLA：",
	"statusPage.uptime.empty": "暂无历史采样数据，系统会在健康采样后自动生成可用率热力图。",
};

export const en: Record<string, string> = {
	"statusPage.desc": "Public safety summary. Hostnames, ports, connection strings, and internal credentials are not exposed.",
	"statusPage.overallLabel": "Overall: ",
	"statusPage.title": "Service Status",
	"statusPage.updatedAt": "Updated at: ",
	"statusPage.health.healthy": "Healthy",
	"statusPage.health.warning": "Warning",
	"statusPage.health.degraded": "Degraded",
	"statusPage.health.critical": "Critical",
	"statusPage.public.detailsHint": "Anonymous visitors can view overall status and a 90-day uptime heatmap (display names only, no host/port). Sign in for component health checks.",
	"statusPage.uptime.title": "Historical uptime (90 days)",
	"statusPage.uptime.desc": "Shows server uptime over the past 90 days.",
	"statusPage.uptime.defaultServerName": "Server",
	"statusPage.uptime.slaLabel": "SLA: ",
	"statusPage.uptime.empty": "No historical samples yet. The heatmap is generated automatically after health sampling runs.",
};
