/**
 * i18n dictionary: `theme.*` (3 keys).
 *
 * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,
 * then re-run the script if you add new prefixes elsewhere.
 */

export const zh: Record<string, string> = {
	"theme.toggleToLight": "切换到浅色模式",
	"theme.toggleToDark": "切换到深色模式",
};

export const en: Record<string, string> = {
	"theme.toggleToLight": "Switch to light mode",
	"theme.toggleToDark": "Switch to dark mode",
};
