/**
 * Sync service — pure command construction (R28 god-file split).
 *
 * Builds the rsync / tar over SSH command strings. No I/O, no prisma, no
 * decryption — those live in `./service-runtime` and `./service-credentials`.
 * Re-exports `shellQuote` for callers that need a stable import path.
 */
import { ValidationError } from "@/lib/errors";
import { isValidTcpPort } from "@/lib/runtime/listen-port";
import { shellQuote } from "@/lib/shell-quote";
import { t } from "@/lib/i18n/service-translations";

export { shellQuote };

/* ── Types ────────────────────────────────────────────────── */

type SyncTargetCommandInput = {
	sourcePath: string;
	targetPath: string;
	targetUser: string;
	targetHost: string;
	targetPort: number;
	keyPath?: string;
	password?: string;
	hostKeySha256?: string | null; // OPEN-2: SSH host key pin for rsync/tar sync
	jobId?: string; // For generating temp known_hosts path
};

type RsyncCommandInput = SyncTargetCommandInput & {
	flags: string[];
};

type TarSyncCommandInput = SyncTargetCommandInput & {
	deleteOrphans: boolean;
};

/* ── Patterns ─────────────────────────────────────────────── */

const SSH_USERNAME_PATTERN = /^[A-Za-z0-9._-]+$/;
const HOSTNAME_PATTERN = /^[A-Za-z0-9._:-]+$/;
const RSYNC_HOST_PATTERN = /^[A-Za-z0-9.:[\]@_-]+$/;

/* ── Sanitisation helpers ─────────────────────────────────── */

function assertSafeSshUsername(username: string): void {
	if (!SSH_USERNAME_PATTERN.test(username) || username.startsWith("-")) {
		throw new ValidationError(t("backend.sync.unsafeSshUsername"));
	}
}

function assertSafeHost(host: string): void {
	if (!HOSTNAME_PATTERN.test(host) || host.startsWith("-")) {
		throw new ValidationError(t("backend.sync.unsafeSshHost"));
	}
}

function formatRsyncHost(host: string): string {
	assertSafeHost(host);
	return host.includes(":") && !host.startsWith("[") ? `[${host}]` : host;
}

function formatSshHost(host: string): string {
	assertSafeHost(host);
	return host.startsWith("[") && host.endsWith("]") ? host.slice(1, -1) : host;
}

function buildRsyncTargetAddress(targetUser: string, targetHost: string): string {
	assertSafeSshUsername(targetUser);
	const address = `${targetUser}@${formatRsyncHost(targetHost)}`;
	if (!RSYNC_HOST_PATTERN.test(address)) {
		throw new ValidationError(t("backend.sync.unsafeRsyncTargetAddress"));
	}
	return address;
}

function buildSshTargetAddress(targetUser: string, targetHost: string): string {
	assertSafeSshUsername(targetUser);
	return `${targetUser}@${formatSshHost(targetHost)}`;
}

function assertSafeSshPort(targetPort: number): void {
	if (!isValidTcpPort(targetPort)) {
		throw new ValidationError(t("backend.sync.unsafeSshPort"));
	}
}

/**
 * Sink for unpinned `UserKnownHostsFile=` in the sync transport. This
 * literal is deliberate: unlike the hub-local NULL_DEVICE (platform-paths),
 * these ssh argv run on the REMOTE source host — always POSIX, always
 * /dev/null. Do not "unify" it with the local null device.
 */
const REMOTE_NULL_DEVICE = "/dev/null";

function buildSshOptions(targetPort: number, hostKeySha256: string | null | undefined, knownHostsPath: string | undefined, quote: TransportQuote): string {
	assertSafeSshPort(targetPort);
	const pinned = Boolean(hostKeySha256?.trim());
	if (pinned && !knownHostsPath) throw new ValidationError(t("backend.sync.pinnedSshSyncRequiresAKnownHostsPath"));
	return [
		`-o StrictHostKeyChecking=${pinned ? "yes" : "accept-new"}`,
		`-o UserKnownHostsFile=${quote(pinned ? knownHostsPath! : REMOTE_NULL_DEVICE)}`,
		`-p ${targetPort}`,
	].join(" ");
}

/* ── Temp-key path ────────────────────────────────────────── */

function safeFileStem(value: string): string {
	return value.replace(/[^A-Za-z0-9_-]/g, "_");
}

export function getSyncTempKeyPath(jobId: string, purpose: "rsync" | "tar" | "known_hosts"): string {
	return `/tmp/app-sync-${purpose}-${safeFileStem(jobId)}`;
}

/* ── Command builders ─────────────────────────────────────── */

function shellDoubleQuote(value: string): string {
	return `"${value.replace(/(["\\$`])/g, "\\$1")}"`;
}

/**
 * How the consumer of a transport string treats quotes.
 *
 * rsync's `--rsh` value is not parsed by a shell: rsync splits it on
 * whitespace and execs the tokens directly, so shell quoting survives into
 * ssh's argv — `-i '/tmp/k'` makes ssh report "Identity file '/tmp/k' not
 * accessible" and silently fall through to another auth method. The tar
 * fallback pipes the same transport into a remote shell, where the quotes are
 * consumed as intended. Each builder therefore picks its own quoting.
 */
type TransportQuote = (value: string) => string;

/**
 * Every path we place inside an rsync transport is generated by
 * {@link getSyncTempKeyPath} (stem filtered to `[A-Za-z0-9_-]`) or is the
 * literal `/dev/null`, so none of them can contain anything that would need
 * quoting. Assert that invariant rather than quoting a value rsync would hand
 * to ssh with the quotes attached.
 */
function assertUnquotedTransportPath(value: string): string {
	if (!/^[A-Za-z0-9._/-]+$/.test(value)) {
		throw new ValidationError(t("backend.sync.unsafeSshTransportPath"));
	}
	return value;
}

/**
 * Build the ssh command that carries the transfer, plus any environment
 * assignment that must be applied to the *outer* command instead of the
 * transport itself.
 */
function buildSshTransport(
	input: SyncTargetCommandInput,
	quote: TransportQuote,
): { transport: string; envPrefix: string } {
	const knownHostsPath = input.hostKeySha256?.trim()
		? getSyncTempKeyPath(input.jobId ?? "sync", "known_hosts")
		: undefined;
	const sshCommand = ["ssh", buildSshOptions(input.targetPort, input.hostKeySha256, knownHostsPath, quote)];
	if (input.keyPath) sshCommand.push("-i", quote(input.keyPath));
	const base = sshCommand.join(" ");
	if (input.password) {
		// SSHPASS keeps the password out of /proc/cmdline. It has to ride on the
		// outer command: rsync would exec a program literally named `SSHPASS=…`
		// ("Failed to exec"), so only the caller's shell can honour it.
		return { transport: `sshpass -e ${base}`, envPrefix: `SSHPASS=${shellQuote(input.password)} ` };
	}
	return { transport: base, envPrefix: "" };
}

function withCredentialCleanup(command: string, input: SyncTargetCommandInput): string {
	const paths = [input.keyPath, input.hostKeySha256?.trim() ? getSyncTempKeyPath(input.jobId ?? "sync", "known_hosts") : undefined].filter((value): value is string => Boolean(value));
	if (paths.length === 0) return command;
	return `trap 'rm -f -- ${paths.map(shellQuote).join(" ")}' EXIT\n${command}`;
}

export function buildRsyncCommand(input: RsyncCommandInput): string {
	const { transport, envPrefix } = buildSshTransport(input, assertUnquotedTransportPath);
	const target = `${buildRsyncTargetAddress(input.targetUser, input.targetHost)}:${input.targetPath.replace(/\/$/, "")}/`;
	const command = `${envPrefix}rsync ${input.flags.join(" ")} -e ${shellDoubleQuote(transport)} ${shellQuote(`${input.sourcePath.replace(/\/$/, "")}/`)} ${shellQuote(target)} 2>&1`;
	return withCredentialCleanup(command, input);
}

export function buildTarSyncCommand(input: TarSyncCommandInput): string {
	const { transport, envPrefix } = buildSshTransport(input, shellQuote);
	const targetAddress = buildSshTargetAddress(input.targetUser, input.targetHost);
	const prepareTarget = input.deleteOrphans
		? `mkdir -p -- ${shellQuote(input.targetPath)} && cd -- ${shellQuote(input.targetPath)} && find . -mindepth 1 -maxdepth 1 -exec rm -rf -- {} + && tar xf - -C ${shellQuote(input.targetPath)}`
		: `mkdir -p -- ${shellQuote(input.targetPath)} && tar xf - -C ${shellQuote(input.targetPath)}`;
	const command = `tar cf - -C ${shellQuote(input.sourcePath)} . | ${envPrefix}${transport} ${shellQuote(targetAddress)} ${shellQuote(prepareTarget)} 2>&1`;
	return withCredentialCleanup(command, input);
}
