-- TR-023 M04: Playbook + PlaybookRun.
--
-- Playbook = durable chain of steps (run_command | send_notification |
-- call_webhook) triggered by a scheduler (cron or metric threshold). The
-- PlaybookRun table is the audit log + executor state machine.
--
-- Manual migration (not generated by `prisma migrate dev`) because the
-- development database has accumulated schema drift from earlier tasks
-- (deployment_snapshots_sourceRunId_fkey, updatedAt defaults, etc.) that
-- is unrelated to M04 and would block an auto-generated diff. This file
-- therefore ONLY contains the M04 changes; the drift is left for a
-- separate housekeeping migration.

CREATE TABLE "playbooks" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "triggerType" TEXT NOT NULL,
    "triggerConfig" JSONB NOT NULL,
    "steps" JSONB NOT NULL,
    "chainRetry" INTEGER NOT NULL DEFAULT 0,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "playbooks_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "playbook_runs" (
    "id" TEXT NOT NULL,
    "playbookId" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'queued',
    "dryRun" BOOLEAN NOT NULL DEFAULT false,
    "triggerContext" JSONB,
    "stepResults" JSONB,
    "errorMessage" TEXT,
    "startedAt" TIMESTAMP(3),
    "completedAt" TIMESTAMP(3),
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "playbook_runs_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "playbooks_enabled_createdAt_idx" ON "playbooks"("enabled", "createdAt");

CREATE INDEX "playbook_runs_playbookId_createdAt_idx" ON "playbook_runs"("playbookId", "createdAt");

CREATE INDEX "playbook_runs_status_createdAt_idx" ON "playbook_runs"("status", "createdAt");

ALTER TABLE "playbooks" ADD CONSTRAINT "playbooks_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "playbook_runs" ADD CONSTRAINT "playbook_runs_playbookId_fkey" FOREIGN KEY ("playbookId") REFERENCES "playbooks"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "playbook_runs" ADD CONSTRAINT "playbook_runs_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
