import type { ServiceTemplate } from "./types";

export const DEVTOOLS_SERVICE_TEMPLATES: ServiceTemplate[] = [
	/* ── 🔧 开发工具 ─────────────────────────────────────────────── */
	{
		slug: "gitea",
		name: "Gitea Git",
		category: "devtools",
		icon: "🔨",
		description: "轻量级自托管 Git 服务，类似 GitHub/GitLab",
		image: "gitea/gitea:latest",
		defaultPort: 3002,
		path: "/gitea/",
		envJson: { USER_UID: "0", USER_GID: "0" },
		volumesJson: [
			{ host: "/opt/gitea/data", container: "/data" },
			{ host: "/etc/timezone", container: "/etc/timezone:ro" },
			{ host: "/etc/localtime", container: "/etc/localtime:ro" },
		],
	},
	{
		slug: "code-server",
		name: "Code Server",
		category: "devtools",
		icon: "💻",
		description: "在浏览器中运行 VS Code，随时随地远程开发",
		image: "linuxserver/code-server:latest",
		defaultPort: 8443,
		path: "/code-server/",
		envJson: { PUID: "0", PGID: "0", PASSWORD: "", SUDO_PASSWORD: "" },
		volumesJson: [{ host: "/opt/code-server/config", container: "/config" }],
	},
	{
		slug: "vaultwarden",
		name: "Vaultwarden 密码",
		category: "devtools",
		icon: "🔐",
		description: "轻量级 Bitwarden 兼容密码管理器，Rust 编写",
		image: "vaultwarden/server:latest",
		defaultPort: 8081,
		path: "/vaultwarden/",
		envJson: {},
		volumesJson: [{ host: "/opt/vaultwarden/data", container: "/data" }],
	},
	{
		slug: "portainer",
		name: "Portainer",
		category: "devtools",
		icon: "🐳",
		description: "Docker 容器可视化管理面板，支持 Swarm/K8s",
		image: "portainer/portainer-ce:latest",
		defaultPort: 9443,
		path: "/portainer/",
		envJson: {},
		volumesJson: [
			{ host: "/opt/portainer/data", container: "/data" },
			{ host: "/var/run/docker.sock", container: "/var/run/docker.sock" },
		],
		allowDockerSocket: true,
		command: "--http-enabled",
	},
	{
		slug: "stirling-pdf",
		name: "Stirling PDF",
		category: "devtools",
		icon: "📄",
		description: "强大的自托管 PDF 工具箱，支持合并/分割/转换/压缩等",
		image: "frooodle/s-pdf:latest",
		defaultPort: 8082,
		path: "/stirling-pdf/",
		envJson: { DOCKER_ENABLE_SECURITY: "false" },
		volumesJson: [{ host: "/opt/stirling-pdf/data", container: "/usr/share/tessdata" }],
	},
	{
		slug: "it-tools",
		name: "IT-Tools",
		category: "devtools",
		icon: "🛠️",
		description: "开发者在线工具箱：加密/解码/转换/正则/UUID等数十种工具",
		image: "corentinth/it-tools:latest",
		defaultPort: 8112,
		path: "/it-tools/",
		envJson: {},
		volumesJson: [],
	},
	{
		slug: "n8n",
		name: "n8n 自动化",
		category: "devtools",
		icon: "🔄",
		description: "开源工作流自动化，连接 400+ 应用，Zapier 替代",
		image: "n8nio/n8n:latest",
		defaultPort: 5678,
		path: "/n8n/",
		envJson: { N8N_BASIC_AUTH_ACTIVE: "true", N8N_BASIC_AUTH_USER: "admin", N8N_BASIC_AUTH_PASSWORD: "admin" },
		volumesJson: [{ host: "/opt/n8n/data", container: "/home/node/.n8n" }],
	},
	{
		slug: "gladys",
		name: "Gladys 助手",
		category: "devtools",
		icon: "🏠",
		description: "开源智能家居平台，支持 MQTT/Zigbee/HomeKit",
		image: "gladysassistant/gladys:latest",
		defaultPort: 8113,
		path: "/gladys/",
		envJson: {},
		volumesJson: [
			{ host: "/opt/gladys/data", container: "/var/lib/gladysassistant" },
			{ host: "/var/run/docker.sock", container: "/var/run/docker.sock" },
		],
	},
];
