import type { ServiceTemplate } from "./types";

export const MEDIA_SERVICE_TEMPLATES: ServiceTemplate[] = [
	/* ── 🎬 媒体影视 ─────────────────────────────────────────────── */
	{
		slug: "emby",
		name: "Emby Media",
		category: "media",
		icon: "🎬",
		description: "Powerful media server to manage and stream your movies, TV shows and music",
		image: "emby/embyserver:latest",
		defaultPort: 8096,
		path: "/web/index.html",
		envJson: { PUID: "0", PGID: "0" },
		volumesJson: [
			{ host: "/opt/emby/config", container: "/config" },
			{ host: "/opt/emby/data", container: "/data" },
		],
	},
	{
		slug: "jellyfin",
		name: "Jellyfin Media",
		category: "media",
		icon: "📺",
		description: "Free open-source media system, an open-source alternative to Emby/Plex",
		image: "jellyfin/jellyfin:latest",
		defaultPort: 8097,
		path: "/jellyfin/",
		envJson: {},
		volumesJson: [
			{ host: "/opt/jellyfin/config", container: "/config" },
			{ host: "/opt/jellyfin/cache", container: "/cache" },
			{ host: "/opt/jellyfin/media", container: "/media" },
		],
	},
	{
		slug: "navidrome",
		name: "Navidrome Music",
		category: "media",
		icon: "🎵",
		description: "Lightweight self-hosted music streaming server, Subsonic compatible",
		image: "deluan/navidrome:latest",
		defaultPort: 4533,
		path: "/navidrome/",
		envJson: { ND_SCANSCHEDULE: "1h", ND_LOGLEVEL: "info", ND_SESSIONTIMEOUT: "24h" },
		volumesJson: [
			{ host: "/opt/navidrome/data", container: "/data" },
			{ host: "/opt/navidrome/music", container: "/music:ro" },
		],
	},
	{
		slug: "photoprism",
		name: "PhotoPrism Photos",
		category: "media",
		icon: "📸",
		description: "AI-powered self-hosted photo management with auto-classification and face recognition",
		image: "photoprism/photoprism:latest",
		defaultPort: 2342,
		path: "/photoprism/",
		envJson: { PHOTOPRISM_ADMIN_PASSWORD: "pleasechange", PHOTOPRISM_AUTH_MODE: "password" },
		volumesJson: [
			{ host: "/opt/photoprism/originals", container: "/photoprism/originals" },
			{ host: "/opt/photoprism/storage", container: "/photoprism/storage" },
		],
	},
	{
		slug: "immich",
		name: "Immich Photos",
		category: "media",
		icon: "🖼️",
		description: "High-performance self-hosted photo/video backup, an open-source alternative to Google Photos",
		image: "ghcr.io/immich-app/immich-server:release",
		defaultPort: 2283,
		path: "/immich/",
		envJson: { DB_HOSTNAME: "127.0.0.1" },
		volumesJson: [
			{ host: "/opt/immich/upload", container: "/usr/src/app/upload" },
		],
	},
	{
		slug: "metube",
		name: "MeTube Downloader",
		category: "media",
		icon: "⬇️",
		description: "Web GUI for YouTube-dl, supports downloading videos from YouTube/Bilibili and more",
		image: "ghcr.io/alexta69/metube:latest",
		defaultPort: 8088,
		path: "/metube/",
		envJson: {},
		volumesJson: [{ host: "/opt/metube/downloads", container: "/downloads" }],
	},
	{
		slug: "komga",
		name: "Komga Comics",
		category: "media",
		icon: "📕",
		description: "Comics/e-book media server, supports CBZ/CBR/EPUB/PDF",
		image: "gotson/komga:latest",
		defaultPort: 8083,
		path: "/komga/",
		envJson: {},
		volumesJson: [
			{ host: "/opt/komga/config", container: "/config" },
			{ host: "/opt/komga/books", container: "/books" },
		],
	},
];
