import type { ServiceTemplate } from "./types";

export const OTHER_SERVICE_TEMPLATES: ServiceTemplate[] = [
	/* ── 🗂️ 其他服务 ─────────────────────────────────────────────── */
	{
		slug: "itdog-tcping",
		name: "ITDog TCPing",
		category: "other",
		icon: "🏓",
		description: "Multi-node TCPing monitoring tool to detect global network connectivity",
		image: "johnserfdev/itdog-tcping:latest",
		defaultPort: 8087,
		path: "/itdog/",
		envJson: {},
		volumesJson: [],
	},
	{
		slug: "qrcode",
		name: "QR Code Generator",
		category: "other",
		icon: "📱",
		description: "Self-hosted QR code generation service, no third-party API needed",
		image: "alexzorin/qrcode-server:latest",
		defaultPort: 8089,
		path: "/qrcode/",
		envJson: {},
		volumesJson: [],
	},
	{
		slug: "dufs",
		name: "Dufs File Sharing",
		category: "other",
		icon: "📤",
		description: "Minimal WebDAV/HTTP file sharing server, written in Rust",
		image: "sigoden/dufs:latest",
		defaultPort: 5001,
		path: "/dufs/",
		envJson: {},
		volumesJson: [{ host: "/opt/dufs/data", container: "/data" }],
	},
	{
		slug: "pairdrop",
		name: "PairDrop File Transfer",
		category: "other",
		icon: "📲",
		description: "Cross-device file transfer, a web open-source alternative to AirDrop",
		image: "lscr.io/linuxserver/pairdrop:latest",
		defaultPort: 3007,
		path: "/pairdrop/",
		envJson: { PUID: "0", PGID: "0" },
		volumesJson: [],
	},
	{
		slug: "tianji",
		name: "Tianji",
		category: "other",
		icon: "🔭",
		description: "All-in-one ops monitoring: website monitoring + server status + alert notifications",
		image: "moonrailway/tianji:latest",
		defaultPort: 3015,
		path: "/tianji/",
		envJson: {},
		volumesJson: [{ host: "/opt/tianji/data", container: "/data" }],
	},
	{
		slug: "lobe-chat",
		name: "LobeChat AI",
		category: "other",
		icon: "🤖",
		description: "Beautiful open-source ChatGPT/LLM chat interface, supports multiple models",
		image: "lobehub/lobe-chat:latest",
		defaultPort: 3016,
		path: "/lobe-chat/",
		envJson: {},
		volumesJson: [],
	},
	{
		slug: "frps",
		name: "FRP Tunnel",
		category: "other",
		icon: "🔗",
		description: "High-performance intranet penetration server, exposes intranet services to the public network",
		image: "snowdreamtech/frps:latest",
		defaultPort: 7500,
		path: "/frps/",
		envJson: {},
		volumesJson: [{ host: "/opt/frps/config", container: "/etc/frp" }],
	},
	{
		slug: "maxtext",
		name: "MaxKB Knowledge Base",
		category: "other",
		icon: "🧠",
		description: "LLM-based knowledge base Q&A system, an open-source RAG solution",
		image: "1panel/maxkb:latest",
		defaultPort: 3017,
		path: "/maxkb/",
		envJson: {},
		volumesJson: [{ host: "/opt/maxkb/data", container: "/var/lib/maxkb" }],
	},
];
