import type { ServiceTemplate } from "./types";

export const STORAGE_SERVICE_TEMPLATES: ServiceTemplate[] = [
	/* ── ☁️ 存储网盘 ─────────────────────────────────────────────── */
	{
		slug: "alist",
		name: "AList Cloud Drive",
		category: "storage",
		icon: "☁️",
		description: "File listing program supporting multiple storage backends, can mount Alibaba Cloud Drive, OneDrive, S3, etc.",
		image: "xhofe/alist:latest",
		defaultPort: 5244,
		path: "/files-proxy/",
		envJson: { PUID: "0", PGID: "0", UMASK: "022" },
		volumesJson: [{ host: "/opt/alist/data", container: "/opt/alist/data" }],
	},
	{
		slug: "nextcloud",
		name: "Nextcloud Drive",
		category: "storage",
		icon: "📁",
		description: "Self-hosted private cloud storage and collaboration platform, supports file sync/calendar/contacts",
		image: "nextcloud:latest",
		defaultPort: 8080,
		internalPort: 80,
		path: "/nextcloud/",
		envJson: {},
		volumesJson: [
			{ host: "/opt/nextcloud/html", container: "/var/www/html" },
			{ host: "/opt/nextcloud/data", container: "/var/www/html/data" },
		],
	},
	{
		slug: "filebrowser",
		name: "File Browser",
		category: "storage",
		icon: "📂",
		description: "Minimal web file manager, supports upload/download/edit/share",
		image: "filebrowser/filebrowser:latest",
		defaultPort: 8110,
		path: "/fb/",
		envJson: {},
		volumesJson: [
			{ host: "/opt/filebrowser/db", container: "/database" },
			{ host: "/opt/filebrowser/config", container: "/config" },
			{ host: "/srv", container: "/srv" },
		],
	},
	{
		slug: "minio",
		name: "MinIO Object Storage",
		category: "storage",
		icon: "🗄️",
		description: "High-performance S3-compatible object storage, suitable for backup/CDN/data lake",
		image: "minio/minio:latest",
		defaultPort: 9001,
		internalPort: 9000,
		path: "/minio/",
		envJson: { MINIO_ROOT_USER: "minioadmin", MINIO_ROOT_PASSWORD: "minioadmin" },
		volumesJson: [{ host: "/opt/minio/data", container: "/data" }],
		command: "server /data --console-address ':9001'",
	},
	{
		slug: "davos",
		name: "Davos Download Manager",
		category: "storage",
		icon: "📥",
		description: "WebDAV/FTP/SFTP automatic sync download manager",
		image: "linuxserver/davos:latest",
		defaultPort: 8111,
		path: "/davos/",
		envJson: { PUID: "0", PGID: "0" },
		volumesJson: [
			{ host: "/opt/davos/config", container: "/config" },
			{ host: "/opt/davos/downloads", container: "/downloads" },
		],
	},
];
