import type { ServiceTemplate } from "./types";

export const NETWORK_SERVICE_TEMPLATES: ServiceTemplate[] = [
	/* ── 🌐 网络监控 ─────────────────────────────────────────────── */
	{
		slug: "uptime-kuma",
		name: "Uptime Kuma",
		category: "network",
		icon: "🟢",
		description: "美观的网站/服务监控工具，支持 HTTP/TCP/DNS/Ping 等多种探针",
		image: "louislam/uptime-kuma:latest",
		defaultPort: 3003,
		path: "/uptime-kuma/",
		envJson: {},
		volumesJson: [{ host: "/opt/uptime-kuma/data", container: "/app/data" }],
	},
	{
		slug: "adguardhome",
		name: "AdGuard Home",
		category: "network",
		icon: "🛡️",
		description: "全网络广告/追踪器拦截 DNS 服务器，Pi-hole 替代",
		image: "adguard/adguardhome:latest",
		defaultPort: 3004,
		internalPort: 3000,
		path: "/adguard/",
		envJson: {},
		volumesJson: [
			{ host: "/opt/adguardhome/work", container: "/opt/adguardhome/work" },
			{ host: "/opt/adguardhome/conf", container: "/opt/adguardhome/conf" },
		],
	},
	{
		slug: "pihole",
		name: "Pi-hole",
		category: "network",
		icon: "🕳️",
		description: "DNS 级广告拦截器，保护全网络免受广告侵扰",
		image: "pihole/pihole:latest",
		defaultPort: 8085,
		internalPort: 80,
		path: "/admin/",
		envJson: { WEBPASSWORD: "changeme", DNS1: "8.8.8.8", DNS2: "8.8.4.4" },
		volumesJson: [
			{ host: "/opt/pihole/etc-pihole", container: "/etc/pihole" },
			{ host: "/opt/pihole/etc-dnsmasq", container: "/etc/dnsmasq.d" },
		],
	},
	{
		slug: "speedtest-tracker",
		name: "SpeedTest 测速",
		category: "network",
		icon: "⚡",
		description: "自动定时网速测试和记录，生成历史趋势图表",
		image: "ghcr.io/alexjustesen/speedtest-tracker:latest",
		defaultPort: 3005,
		path: "/speedtest/",
		envJson: { PUID: "0", PGID: "0" },
		volumesJson: [{ host: "/opt/speedtest/config", container: "/config" }],
	},
	{
		slug: "beszel",
		name: "Beszel 监控",
		category: "network",
		icon: "📊",
		description: "轻量级服务器监控面板，CPU/内存/磁盘/网络实时图表",
		image: "henrygd/beszel:latest",
		defaultPort: 3006,
		path: "/beszel/",
		envJson: {},
		volumesJson: [{ host: "/opt/beszel/data", container: "/data" }],
	},
	{
		slug: "changedetection",
		name: "ChangeDetec 变更",
		category: "network",
		icon: "👁️",
		description: "网页变更监控，自动检测页面内容变化并通知",
		image: "dgtlmoon/changedetection.io:latest",
		defaultPort: 5000,
		path: "/changedetection/",
		envJson: {},
		volumesJson: [{ host: "/opt/changedetection/data", container: "/datastore" }],
	},
];
