import type { ServiceTemplate } from "./types";

export const BLOG_SERVICE_TEMPLATES: ServiceTemplate[] = [
	/* ── ✍️ 博客建站 ─────────────────────────────────────────────── */
	{
		slug: "halo",
		name: "Halo Blog",
		category: "blog",
		icon: "✍️",
		description: "Powerful Java open-source blog/CMS system, rich theme/plugin ecosystem",
		image: "halohub/halo:latest",
		defaultPort: 8090,
		path: "/halo/",
		envJson: { HALO_SECURITY_INITIALIZER_SUPERADMINUSERNAME: "admin", HALO_SECURITY_INITIALIZER_SUPERADMINPASSWORD: "admin123" },
		volumesJson: [{ host: "/opt/halo/data", container: "/root/.halo2" }],
	},
	{
		slug: "ghost",
		name: "Ghost Blog",
		category: "blog",
		icon: "👻",
		description: "Professional open-source blog/Newsletter platform, a WordPress alternative",
		image: "ghost:latest",
		defaultPort: 2368,
		path: "/ghost/",
		envJson: { url: "http://localhost:2368" },
		volumesJson: [{ host: "/opt/ghost/content", container: "/var/lib/ghost/content" }],
	},
	{
		slug: "wordpress",
		name: "WordPress",
		category: "blog",
		icon: "🌐",
		description: "The world's most popular CMS, an unmatched plugin/theme ecosystem",
		image: "wordpress:latest",
		defaultPort: 8084,
		internalPort: 80,
		path: "/wordpress/",
		envJson: { WORDPRESS_DB_HOST: "127.0.0.1", WORDPRESS_DB_USER: "root", WORDPRESS_DB_PASSWORD: "", WORDPRESS_DB_NAME: "wordpress" },
		volumesJson: [{ host: "/opt/wordpress/data", container: "/var/www/html" }],
	},
	{
		slug: "typecho",
		name: "Typecho Blog",
		category: "blog",
		icon: "📝",
		description: "Lightweight PHP blog system, minimal and efficient",
		image: "joyqi/typecho:latest",
		defaultPort: 8086,
		internalPort: 80,
		path: "/typecho/",
		envJson: {},
		volumesJson: [{ host: "/opt/typecho/data", container: "/app/usr" }],
	},
];
