import type { ServiceTemplate } from "./types";

export const BLOG_SERVICE_TEMPLATES: ServiceTemplate[] = [
	/* ── ✍️ 博客建站 ─────────────────────────────────────────────── */
	{
		slug: "halo",
		name: "Halo 博客",
		category: "blog",
		icon: "✍️",
		description: "强大的 Java 开源博客/CMS 系统，主题/插件生态丰富",
		image: "halohub/halo:latest",
		defaultPort: 8090,
		path: "/halo/",
		envJson: { HALO_SECURITY_INITIALIZER_SUPERADMINUSERNAME: "admin", HALO_SECURITY_INITIALIZER_SUPERADMINPASSWORD: "admin123" },
		volumesJson: [{ host: "/opt/halo/data", container: "/root/.halo2" }],
	},
	{
		slug: "ghost",
		name: "Ghost 博客",
		category: "blog",
		icon: "👻",
		description: "专业级开源博客/Newsletter 平台，WordPress 替代",
		image: "ghost:latest",
		defaultPort: 2368,
		path: "/ghost/",
		envJson: { url: "http://localhost:2368" },
		volumesJson: [{ host: "/opt/ghost/content", container: "/var/lib/ghost/content" }],
	},
	{
		slug: "wordpress",
		name: "WordPress",
		category: "blog",
		icon: "🌐",
		description: "全球最流行的 CMS，插件/主题生态无可匹敌",
		image: "wordpress:latest",
		defaultPort: 8084,
		internalPort: 80,
		path: "/wordpress/",
		envJson: { WORDPRESS_DB_HOST: "127.0.0.1", WORDPRESS_DB_USER: "root", WORDPRESS_DB_PASSWORD: "", WORDPRESS_DB_NAME: "wordpress" },
		volumesJson: [{ host: "/opt/wordpress/data", container: "/var/www/html" }],
	},
	{
		slug: "typecho",
		name: "Typecho 博客",
		category: "blog",
		icon: "📝",
		description: "轻量级 PHP 博客系统，极简高效",
		image: "joyqi/typecho:latest",
		defaultPort: 8086,
		internalPort: 80,
		path: "/typecho/",
		envJson: {},
		volumesJson: [{ host: "/opt/typecho/data", container: "/app/usr" }],
	},
];
