import type { ServiceTemplate } from "./types";

export const OTHER_SERVICE_TEMPLATES: ServiceTemplate[] = [
	/* ── 🗂️ 其他服务 ─────────────────────────────────────────────── */
	{
		slug: "itdog-tcping",
		name: "ITDog TCPing",
		category: "other",
		icon: "🏓",
		description: "多节点 TCPing 监测工具，检测全球网络连通性",
		image: "johnserfdev/itdog-tcping:latest",
		defaultPort: 8087,
		path: "/itdog/",
		envJson: {},
		volumesJson: [],
	},
	{
		slug: "qrcode",
		name: "QR Code 生成",
		category: "other",
		icon: "📱",
		description: "自托管二维码生成服务，无需第三方 API",
		image: "alexzorin/qrcode-server:latest",
		defaultPort: 8089,
		path: "/qrcode/",
		envJson: {},
		volumesJson: [],
	},
	{
		slug: "dufs",
		name: "Dufs 文件分享",
		category: "other",
		icon: "📤",
		description: "极简的 WebDAV/HTTP 文件分享服务器，Rust 编写",
		image: "sigoden/dufs:latest",
		defaultPort: 5001,
		path: "/dufs/",
		envJson: {},
		volumesJson: [{ host: "/opt/dufs/data", container: "/data" }],
	},
	{
		slug: "pairdrop",
		name: "PairDrop 传文件",
		category: "other",
		icon: "📲",
		description: "跨设备文件传输，AirDrop 的 Web 开源替代",
		image: "lscr.io/linuxserver/pairdrop:latest",
		defaultPort: 3007,
		path: "/pairdrop/",
		envJson: { PUID: "0", PGID: "0" },
		volumesJson: [],
	},
	{
		slug: "tianji",
		name: "Tianji 天迹",
		category: "other",
		icon: "🔭",
		description: "一体化运维监控：网站监测+服务器状态+通知告警",
		image: "moonrailway/tianji:latest",
		defaultPort: 3015,
		path: "/tianji/",
		envJson: {},
		volumesJson: [{ host: "/opt/tianji/data", container: "/data" }],
	},
	{
		slug: "lobe-chat",
		name: "LobeChat AI",
		category: "other",
		icon: "🤖",
		description: "美观的开源 ChatGPT/LLM 聊天界面，支持多模型",
		image: "lobehub/lobe-chat:latest",
		defaultPort: 3016,
		path: "/lobe-chat/",
		envJson: {},
		volumesJson: [],
	},
	{
		slug: "frps",
		name: "FRP 内网穿透",
		category: "other",
		icon: "🔗",
		description: "高性能内网穿透服务器，将内网服务暴露到公网",
		image: "snowdreamtech/frps:latest",
		defaultPort: 7500,
		path: "/frps/",
		envJson: {},
		volumesJson: [{ host: "/opt/frps/config", container: "/etc/frp" }],
	},
	{
		slug: "maxtext",
		name: "MaxKB 知识库",
		category: "other",
		icon: "🧠",
		description: "基于 LLM 的知识库问答系统，RAG 开源方案",
		image: "1panel/maxkb:latest",
		defaultPort: 3017,
		path: "/maxkb/",
		envJson: {},
		volumesJson: [{ host: "/opt/maxkb/data", container: "/var/lib/maxkb" }],
	},
];
