import type { ServiceTemplate } from "./types";

export const NOTES_SERVICE_TEMPLATES: ServiceTemplate[] = [
	/* ── 📝 笔记文档 ─────────────────────────────────────────────── */
	{
		slug: "memos",
		name: "Memos 笔记",
		category: "notes",
		icon: "📝",
		description: "轻量级自托管备忘录/笔记服务，Flomo 替代",
		image: "neosmemo/memos:latest",
		defaultPort: 5230,
		path: "/memos/",
		envJson: {},
		volumesJson: [{ host: "/opt/memos/data", container: "/var/opt/memos" }],
	},
	{
		slug: "outline",
		name: "Outline 知识库",
		category: "notes",
		icon: "📖",
		description: "美观的团队知识库/Wiki，Notion 开源替代",
		image: "outlinewiki/outline:latest",
		defaultPort: 3010,
		path: "/outline/",
		envJson: { PGSSLMODE: "disable" },
		volumesJson: [{ host: "/opt/outline/data", container: "/var/lib/outline/data" }],
	},
	{
		slug: "hedgedoc",
		name: "HedgeDoc 协作",
		category: "notes",
		icon: "📑",
		description: "实时协作 Markdown 编辑器，多人同时编辑",
		image: "quay.io/hedgedoc/hedgedoc:latest",
		defaultPort: 3011,
		path: "/hedgedoc/",
		envJson: {},
		volumesJson: [{ host: "/opt/hedgedoc/uploads", container: "/hedgedoc/public/uploads" }],
	},
	{
		slug: "affine",
		name: "AFFiNE 工作区",
		category: "notes",
		icon: "🧩",
		description: "一体化工作区：文档/白板/数据库，Notion+Miro 替代",
		image: "ghcr.io/toeverything/affine-self-hosted:latest",
		defaultPort: 3012,
		path: "/affine/",
		envJson: {},
		volumesJson: [{ host: "/opt/affine/data", container: "/root/.affine" }],
	},
	{
		slug: "linkwarden",
		name: "Linkwarden 书签",
		category: "notes",
		icon: "🔖",
		description: "自托管书签管理器，自动抓取网页快照/截图",
		image: "ghcr.io/linkwarden/linkwarden:latest",
		defaultPort: 3013,
		path: "/linkwarden/",
		envJson: {},
		volumesJson: [{ host: "/opt/linkwarden/data", container: "/data/data" }],
	},
	{
		slug: "wallabag",
		name: "Wallabag 稍后读",
		category: "notes",
		icon: "📰",
		description: "自托管稍后读服务，保存网页文章离线阅读",
		image: "wallabag/wallabag:latest",
		defaultPort: 3014,
		path: "/wallabag/",
		envJson: {},
		volumesJson: [
			{ host: "/opt/wallabag/images", container: "/var/www/wallabag/web/assets/images" },
			{ host: "/opt/wallabag/data", container: "/var/www/wallabag/data" },
		],
	},
];
