import type { ServiceTemplate } from "./types";

export const STORAGE_SERVICE_TEMPLATES: ServiceTemplate[] = [
	/* ── ☁️ 存储网盘 ─────────────────────────────────────────────── */
	{
		slug: "alist",
		name: "AList 云盘",
		category: "storage",
		icon: "☁️",
		description: "支持多种存储的文件列表程序，可挂载阿里云盘、OneDrive、S3等",
		image: "xhofe/alist:latest",
		defaultPort: 5244,
		path: "/files-proxy/",
		envJson: { PUID: "0", PGID: "0", UMASK: "022" },
		volumesJson: [{ host: "/opt/alist/data", container: "/opt/alist/data" }],
	},
	{
		slug: "nextcloud",
		name: "Nextcloud 网盘",
		category: "storage",
		icon: "📁",
		description: "自托管的私有云存储和协作平台，支持文件同步/日历/联系人",
		image: "nextcloud:latest",
		defaultPort: 8080,
		internalPort: 80,
		path: "/nextcloud/",
		envJson: {},
		volumesJson: [
			{ host: "/opt/nextcloud/html", container: "/var/www/html" },
			{ host: "/opt/nextcloud/data", container: "/var/www/html/data" },
		],
	},
	{
		slug: "filebrowser",
		name: "File Browser",
		category: "storage",
		icon: "📂",
		description: "极简的 Web 文件管理器，支持上传/下载/编辑/分享",
		image: "filebrowser/filebrowser:latest",
		defaultPort: 8110,
		path: "/fb/",
		envJson: {},
		volumesJson: [
			{ host: "/opt/filebrowser/db", container: "/database" },
			{ host: "/opt/filebrowser/config", container: "/config" },
			{ host: "/srv", container: "/srv" },
		],
	},
	{
		slug: "minio",
		name: "MinIO 对象存储",
		category: "storage",
		icon: "🗄️",
		description: "高性能 S3 兼容对象存储，适合备份/CDN/数据湖",
		image: "minio/minio:latest",
		defaultPort: 9001,
		internalPort: 9000,
		path: "/minio/",
		envJson: { MINIO_ROOT_USER: "minioadmin", MINIO_ROOT_PASSWORD: "minioadmin" },
		volumesJson: [{ host: "/opt/minio/data", container: "/data" }],
		command: "server /data --console-address ':9001'",
	},
	{
		slug: "davos",
		name: "Davos 下载管理",
		category: "storage",
		icon: "📥",
		description: "WebDAV/FTP/SFTP 自动同步下载管理器",
		image: "linuxserver/davos:latest",
		defaultPort: 8111,
		path: "/davos/",
		envJson: { PUID: "0", PGID: "0" },
		volumesJson: [
			{ host: "/opt/davos/config", container: "/config" },
			{ host: "/opt/davos/downloads", container: "/downloads" },
		],
	},
];
