import type { ServiceTemplate } from "./types";

export const MEDIA_SERVICE_TEMPLATES: ServiceTemplate[] = [
	/* ── 🎬 媒体影视 ─────────────────────────────────────────────── */
	{
		slug: "emby",
		name: "Emby 影视",
		category: "media",
		icon: "🎬",
		description: "强大的媒体服务器，管理和串流你的电影、电视剧和音乐",
		image: "emby/embyserver:latest",
		defaultPort: 8096,
		path: "/web/index.html",
		envJson: { PUID: "0", PGID: "0" },
		volumesJson: [
			{ host: "/opt/emby/config", container: "/config" },
			{ host: "/opt/emby/data", container: "/data" },
		],
	},
	{
		slug: "jellyfin",
		name: "Jellyfin 影视",
		category: "media",
		icon: "📺",
		description: "开源免费的媒体系统，Emby/Plex 的开源替代",
		image: "jellyfin/jellyfin:latest",
		defaultPort: 8097,
		path: "/jellyfin/",
		envJson: {},
		volumesJson: [
			{ host: "/opt/jellyfin/config", container: "/config" },
			{ host: "/opt/jellyfin/cache", container: "/cache" },
			{ host: "/opt/jellyfin/media", container: "/media" },
		],
	},
	{
		slug: "navidrome",
		name: "Navidrome 音乐",
		category: "media",
		icon: "🎵",
		description: "轻量级自托管音乐流媒体服务器，Subsonic 兼容",
		image: "deluan/navidrome:latest",
		defaultPort: 4533,
		path: "/navidrome/",
		envJson: { ND_SCANSCHEDULE: "1h", ND_LOGLEVEL: "info", ND_SESSIONTIMEOUT: "24h" },
		volumesJson: [
			{ host: "/opt/navidrome/data", container: "/data" },
			{ host: "/opt/navidrome/music", container: "/music:ro" },
		],
	},
	{
		slug: "photoprism",
		name: "PhotoPrism 相册",
		category: "media",
		icon: "📸",
		description: "AI 驱动的自托管照片管理，自动分类和人脸识别",
		image: "photoprism/photoprism:latest",
		defaultPort: 2342,
		path: "/photoprism/",
		envJson: { PHOTOPRISM_ADMIN_PASSWORD: "pleasechange", PHOTOPRISM_AUTH_MODE: "password" },
		volumesJson: [
			{ host: "/opt/photoprism/originals", container: "/photoprism/originals" },
			{ host: "/opt/photoprism/storage", container: "/photoprism/storage" },
		],
	},
	{
		slug: "immich",
		name: "Immich 相册",
		category: "media",
		icon: "🖼️",
		description: "高性能自托管照片/视频备份，Google Photos 开源替代",
		image: "ghcr.io/immich-app/immich-server:release",
		defaultPort: 2283,
		path: "/immich/",
		envJson: { DB_HOSTNAME: "127.0.0.1" },
		volumesJson: [
			{ host: "/opt/immich/upload", container: "/usr/src/app/upload" },
		],
	},
	{
		slug: "metube",
		name: "MeTube 下载",
		category: "media",
		icon: "⬇️",
		description: "YouTube-dl 的 Web GUI，支持 YouTube/B站等视频下载",
		image: "ghcr.io/alexta69/metube:latest",
		defaultPort: 8088,
		path: "/metube/",
		envJson: {},
		volumesJson: [{ host: "/opt/metube/downloads", container: "/downloads" }],
	},
	{
		slug: "komga",
		name: "Komga 漫画",
		category: "media",
		icon: "📕",
		description: "漫画/电子书媒体服务器，支持 CBZ/CBR/EPUB/PDF",
		image: "gotson/komga:latest",
		defaultPort: 8083,
		path: "/komga/",
		envJson: {},
		volumesJson: [
			{ host: "/opt/komga/config", container: "/config" },
			{ host: "/opt/komga/books", container: "/books" },
		],
	},
];
