import type { ServiceTemplate } from "./types";

export const NOTES_SERVICE_TEMPLATES: ServiceTemplate[] = [
	/* ── 📝 笔记文档 ─────────────────────────────────────────────── */
	{
		slug: "memos",
		name: "Memos Notes",
		category: "notes",
		icon: "📝",
		description: "Lightweight self-hosted memo/notes service, a Flomo alternative",
		image: "neosmemo/memos:latest",
		defaultPort: 5230,
		path: "/memos/",
		envJson: {},
		volumesJson: [{ host: "/opt/memos/data", container: "/var/opt/memos" }],
	},
	{
		slug: "outline",
		name: "Outline Knowledge Base",
		category: "notes",
		icon: "📖",
		description: "Beautiful team knowledge base/Wiki, an open-source alternative to Notion",
		image: "outlinewiki/outline:latest",
		defaultPort: 3010,
		path: "/outline/",
		envJson: { PGSSLMODE: "disable" },
		volumesJson: [{ host: "/opt/outline/data", container: "/var/lib/outline/data" }],
	},
	{
		slug: "hedgedoc",
		name: "HedgeDoc Collaboration",
		category: "notes",
		icon: "📑",
		description: "Real-time collaborative Markdown editor, multi-user simultaneous editing",
		image: "quay.io/hedgedoc/hedgedoc:latest",
		defaultPort: 3011,
		path: "/hedgedoc/",
		envJson: {},
		volumesJson: [{ host: "/opt/hedgedoc/uploads", container: "/hedgedoc/public/uploads" }],
	},
	{
		slug: "affine",
		name: "AFFiNE Workspace",
		category: "notes",
		icon: "🧩",
		description: "All-in-one workspace: docs/whiteboard/database, an alternative to Notion+Miro",
		image: "ghcr.io/toeverything/affine-self-hosted:latest",
		defaultPort: 3012,
		path: "/affine/",
		envJson: {},
		volumesJson: [{ host: "/opt/affine/data", container: "/root/.affine" }],
	},
	{
		slug: "linkwarden",
		name: "Linkwarden Bookmarks",
		category: "notes",
		icon: "🔖",
		description: "Self-hosted bookmark manager, auto-captures webpage snapshots/screenshots",
		image: "ghcr.io/linkwarden/linkwarden:latest",
		defaultPort: 3013,
		path: "/linkwarden/",
		envJson: {},
		volumesJson: [{ host: "/opt/linkwarden/data", container: "/data/data" }],
	},
	{
		slug: "wallabag",
		name: "Wallabag Read Later",
		category: "notes",
		icon: "📰",
		description: "Self-hosted read-later service, saves web articles for offline reading",
		image: "wallabag/wallabag:latest",
		defaultPort: 3014,
		path: "/wallabag/",
		envJson: {},
		volumesJson: [
			{ host: "/opt/wallabag/images", container: "/var/www/wallabag/web/assets/images" },
			{ host: "/opt/wallabag/data", container: "/var/www/wallabag/data" },
		],
	},
];
