import type { ServiceTemplate } from "./types";

export const DEVTOOLS_SERVICE_TEMPLATES: ServiceTemplate[] = [
	/* ── 🔧 开发工具 ─────────────────────────────────────────────── */
	{
		slug: "gitea",
		name: "Gitea Git",
		category: "devtools",
		icon: "🔨",
		description: "Lightweight self-hosted Git service, similar to GitHub/GitLab",
		image: "gitea/gitea:latest",
		defaultPort: 3002,
		path: "/gitea/",
		envJson: { USER_UID: "0", USER_GID: "0" },
		volumesJson: [
			{ host: "/opt/gitea/data", container: "/data" },
			{ host: "/etc/timezone", container: "/etc/timezone:ro" },
			{ host: "/etc/localtime", container: "/etc/localtime:ro" },
		],
	},
	{
		slug: "code-server",
		name: "Code Server",
		category: "devtools",
		icon: "💻",
		description: "Run VS Code in the browser, remote development anywhere, anytime",
		image: "linuxserver/code-server:latest",
		defaultPort: 8443,
		path: "/code-server/",
		envJson: { PUID: "0", PGID: "0", PASSWORD: "", SUDO_PASSWORD: "" },
		volumesJson: [{ host: "/opt/code-server/config", container: "/config" }],
	},
	{
		slug: "vaultwarden",
		name: "Vaultwarden Password Manager",
		category: "devtools",
		icon: "🔐",
		description: "Lightweight Bitwarden-compatible password manager, written in Rust",
		image: "vaultwarden/server:latest",
		defaultPort: 8081,
		path: "/vaultwarden/",
		envJson: {},
		volumesJson: [{ host: "/opt/vaultwarden/data", container: "/data" }],
	},
	{
		slug: "portainer",
		name: "Portainer",
		category: "devtools",
		icon: "🐳",
		description: "Docker container visual management panel, supports Swarm/K8s",
		image: "portainer/portainer-ce:latest",
		defaultPort: 9443,
		path: "/portainer/",
		envJson: {},
		volumesJson: [
			{ host: "/opt/portainer/data", container: "/data" },
			{ host: "/var/run/docker.sock", container: "/var/run/docker.sock" },
		],
		allowDockerSocket: true,
		command: "--http-enabled",
	},
	{
		slug: "stirling-pdf",
		name: "Stirling PDF",
		category: "devtools",
		icon: "📄",
		description: "Powerful self-hosted PDF toolbox, supports merge/split/convert/compress and more",
		image: "frooodle/s-pdf:latest",
		defaultPort: 8082,
		path: "/stirling-pdf/",
		envJson: { DOCKER_ENABLE_SECURITY: "false" },
		volumesJson: [{ host: "/opt/stirling-pdf/data", container: "/usr/share/tessdata" }],
	},
	{
		slug: "it-tools",
		name: "IT-Tools",
		category: "devtools",
		icon: "🛠️",
		description: "Developer online toolbox: encryption/decoding/conversion/regex/UUID and dozens of tools",
		image: "corentinth/it-tools:latest",
		defaultPort: 8112,
		path: "/it-tools/",
		envJson: {},
		volumesJson: [],
	},
	{
		slug: "n8n",
		name: "n8n Automation",
		category: "devtools",
		icon: "🔄",
		description: "Open-source workflow automation, connects 400+ apps, a Zapier alternative",
		image: "n8nio/n8n:latest",
		defaultPort: 5678,
		path: "/n8n/",
		envJson: { N8N_BASIC_AUTH_ACTIVE: "true", N8N_BASIC_AUTH_USER: "admin", N8N_BASIC_AUTH_PASSWORD: "admin" },
		volumesJson: [{ host: "/opt/n8n/data", container: "/home/node/.n8n" }],
	},
	{
		slug: "gladys",
		name: "Gladys Assistant",
		category: "devtools",
		icon: "🏠",
		description: "Open-source smart home platform, supports MQTT/Zigbee/HomeKit",
		image: "gladysassistant/gladys:latest",
		defaultPort: 8113,
		path: "/gladys/",
		envJson: {},
		volumesJson: [
			{ host: "/opt/gladys/data", container: "/var/lib/gladysassistant" },
			{ host: "/var/run/docker.sock", container: "/var/run/docker.sock" },
		],
	},
];
