import type { ServiceTemplate } from "./types";

export const NETWORK_SERVICE_TEMPLATES: ServiceTemplate[] = [
	/* ── 🌐 网络监控 ─────────────────────────────────────────────── */
	{
		slug: "uptime-kuma",
		name: "Uptime Kuma",
		category: "network",
		icon: "🟢",
		description: "Beautiful website/service monitoring tool, supports HTTP/TCP/DNS/Ping and more probes",
		image: "louislam/uptime-kuma:latest",
		defaultPort: 3003,
		path: "/uptime-kuma/",
		envJson: {},
		volumesJson: [{ host: "/opt/uptime-kuma/data", container: "/app/data" }],
	},
	{
		slug: "adguardhome",
		name: "AdGuard Home",
		category: "network",
		icon: "🛡️",
		description: "Network-wide ad/tracker blocking DNS server, a Pi-hole alternative",
		image: "adguard/adguardhome:latest",
		defaultPort: 3004,
		internalPort: 3000,
		path: "/adguard/",
		envJson: {},
		volumesJson: [
			{ host: "/opt/adguardhome/work", container: "/opt/adguardhome/work" },
			{ host: "/opt/adguardhome/conf", container: "/opt/adguardhome/conf" },
		],
	},
	{
		slug: "pihole",
		name: "Pi-hole",
		category: "network",
		icon: "🕳️",
		description: "DNS-level ad blocker, protects the entire network from ads",
		image: "pihole/pihole:latest",
		defaultPort: 8085,
		internalPort: 80,
		path: "/admin/",
		envJson: { WEBPASSWORD: "changeme", DNS1: "8.8.8.8", DNS2: "8.8.4.4" },
		volumesJson: [
			{ host: "/opt/pihole/etc-pihole", container: "/etc/pihole" },
			{ host: "/opt/pihole/etc-dnsmasq", container: "/etc/dnsmasq.d" },
		],
	},
	{
		slug: "speedtest-tracker",
		name: "SpeedTest Tracker",
		category: "network",
		icon: "⚡",
		description: "Automatic scheduled network speed testing and recording, generates historical trend charts",
		image: "ghcr.io/alexjustesen/speedtest-tracker:latest",
		defaultPort: 3005,
		path: "/speedtest/",
		envJson: { PUID: "0", PGID: "0" },
		volumesJson: [{ host: "/opt/speedtest/config", container: "/config" }],
	},
	{
		slug: "beszel",
		name: "Beszel Monitoring",
		category: "network",
		icon: "📊",
		description: "Lightweight server monitoring panel, real-time CPU/memory/disk/network charts",
		image: "henrygd/beszel:latest",
		defaultPort: 3006,
		path: "/beszel/",
		envJson: {},
		volumesJson: [{ host: "/opt/beszel/data", container: "/data" }],
	},
	{
		slug: "changedetection",
		name: "ChangeDetection",
		category: "network",
		icon: "👁️",
		description: "Webpage change monitoring, auto-detects page content changes and notifies",
		image: "dgtlmoon/changedetection.io:latest",
		defaultPort: 5000,
		path: "/changedetection/",
		envJson: {},
		volumesJson: [{ host: "/opt/changedetection/data", container: "/datastore" }],
	},
];
