-- TR-032 E02: Smart AI ops (recommendation + autonomous modes).
--
-- Manual migration (not generated by `prisma migrate dev`) because the
-- development database has accumulated schema drift from earlier tasks
-- that is unrelated to E02 and would block an auto-generated diff. This
-- file therefore ONLY contains the E02 changes; the drift is left for a
-- separate housekeeping migration.
--
-- Model:
--   ai_ops_logs — one row per AI ops scan / recommendation / autonomous
--                 action. Source of truth for the /ai-ops UI page and
--                 audit trail. Findings + actions are stored as JSONB
--                 to avoid an extra join table for v1.
--
-- Indexes are sized for the typical UI queries:
--   - list-recent : ORDER BY createdAt DESC
--   - filter-by-status + recent : (status, createdAt) DESC
--   - filter-by-mode + recent : (mode, createdAt) DESC
--   - filter-by-user : (triggeredById, createdAt) DESC

CREATE TABLE "ai_ops_logs" (
    "id" TEXT NOT NULL,
    "triggerType" TEXT NOT NULL,
    "mode" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "findings" JSONB NOT NULL DEFAULT '[]',
    "actions" JSONB NOT NULL DEFAULT '[]',
    "notes" TEXT,
    "errorMessage" TEXT,
    "providerId" TEXT,
    "startedAt" TIMESTAMP(3),
    "completedAt" TIMESTAMP(3),
    "durationMs" INTEGER,
    "triggeredById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ai_ops_logs_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "ai_ops_logs_createdAt_idx" ON "ai_ops_logs"("createdAt");
CREATE INDEX "ai_ops_logs_status_createdAt_idx" ON "ai_ops_logs"("status", "createdAt");
CREATE INDEX "ai_ops_logs_mode_createdAt_idx" ON "ai_ops_logs"("mode", "createdAt");
CREATE INDEX "ai_ops_logs_triggeredById_createdAt_idx" ON "ai_ops_logs"("triggeredById", "createdAt");

ALTER TABLE "ai_ops_logs" ADD CONSTRAINT "ai_ops_logs_triggeredById_fkey" FOREIGN KEY ("triggeredById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
