#!/usr/bin/env python3
"""
One-shot script: split src/lib/i18n/translations.ts into per-dictionary files.

Reads the current translations.ts (single zh + en object literal pair),
splits keys by their first segment (e.g. `alertRulesPage.title` → `alertRulesPage`),
and writes one file per prefix under `src/lib/i18n/dictionaries/`. Then
rewrites translations.ts to import each dictionary and spread the values
into the runtime `translations` map.

This script is intentionally idempotent — running it twice produces the same
output. It writes to disk, so back up first or rely on git.

Run: `python3 scripts/i18n-split-dictionaries.py`
"""
import os
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path("/opt/VControlHub")
SRC = ROOT / "src/lib/i18n"
DICTS = SRC / "dictionaries"
DICTS.mkdir(exist_ok=True)

TRANS_FILE = SRC / "translations.ts"
content = TRANS_FILE.read_text(encoding="utf8")

# 1. Locate the zh: { ... } and en: { ... } blocks.
# The format is: \tzh: {\n\t\t"key": "value",\n\t\t...\n\t},\n\ten: {\n ...
# We find them by scanning the `zh:` and `en:` opening markers and matching braces.
def extract_block(text: str, start_marker: str) -> tuple[str, int, int]:
    """Return (block_contents, block_start, block_end) for the block following `start_marker`."""
    m = re.search(rf"^\t{re.escape(start_marker)}:\s*\{{", text, re.MULTILINE)
    if not m:
        raise RuntimeError(f"Could not find block `{start_marker}:`")
    open_brace_pos = text.index("{", m.start())
    depth = 0
    i = open_brace_pos
    while i < len(text):
        c = text[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return text[open_brace_pos + 1 : i], m.start(), i + 1
        i += 1
    raise RuntimeError(f"Unterminated block `{start_marker}:`")

zh_block, _, zh_end = extract_block(content, "zh")
en_block, _, en_end = extract_block(content, "en")

# 2. Parse each block into a dict of key -> value. Values may be raw strings
# (we don't need to interpret them — we just round-trip the literal text).
ENTRY_RE = re.compile(r'^\t\t"([^"]+)":\s*("(?:[^"\\]|\\.)*")', re.MULTILINE)

def parse_block(block: str) -> dict[str, str]:
    out: dict[str, str] = {}
    for m in ENTRY_RE.finditer(block):
        key, value = m.group(1), m.group(2)
        out[key] = value
    return out

zh = parse_block(zh_block)
en = parse_block(en_block)

assert set(zh.keys()) == set(en.keys()), (
    f"zh/en key mismatch: only-in-zh={set(zh)-set(en)}, only-in-en={set(en)-set(zh)}"
)

print(f"[ok] parsed {len(zh)} keys (zh/en matched)")

# 3. Group by first prefix.
by_prefix_zh: dict[str, dict[str, str]] = defaultdict(dict)
by_prefix_en: dict[str, dict[str, str]] = defaultdict(dict)
for k, v in zh.items():
    by_prefix_zh[k.split(".", 1)[0]][k] = v
for k, v in en.items():
    by_prefix_en[k.split(".", 1)[0]][k] = v

# 4. Write one file per prefix.
written: list[str] = []
for prefix in sorted(by_prefix_zh.keys()):
    zh_dict = by_prefix_zh[prefix]
    en_dict = by_prefix_en[prefix]
    # File name: kebab-case the camelCase prefix.
    file_name = re.sub(r"(?<!^)(?=[A-Z])", "-", prefix).lower() + ".ts"
    path = DICTS / file_name
    lines: list[str] = []
    lines.append("/**")
    lines.append(f" * i18n dictionary: `{prefix}.*` ({len(zh_dict)} keys).")
    lines.append(" *")
    lines.append(" * Generated by `scripts/i18n-split-dictionaries.py` — edit keys here,")
    lines.append(" * then re-run the script if you add new prefixes elsewhere.")
    lines.append(" */")
    lines.append("")
    lines.append('export const zh: Record<string, string> = {')
    for k in sorted(zh_dict.keys()):
        # Keys contain dots (e.g. `users.desc.manage`) and must be string literals,
        # not bare identifiers.
        lines.append(f'\t"{k}": {zh_dict[k]},')
    lines.append("};")
    lines.append("")
    lines.append('export const en: Record<string, string> = {')
    for k in sorted(en_dict.keys()):
        lines.append(f'\t"{k}": {en_dict[k]},')
    lines.append("};")
    path.write_text("\n".join(lines) + "\n", encoding="utf8")
    written.append(file_name)
    print(f"  [write] {file_name} ({len(zh_dict)} keys)")

# 5. Rewrite translations.ts to import each dictionary and spread.
# Locate the entire `translations = { ... }` literal so we can replace it.
# The structure: `export const translations: Record<Locale, Record<string, string>> = {\n\tzh: { ... },\n\ten: { ... },\n};`
# We just replace the zh: { ... } and en: { ... } contents.
new_trans_lines: list[str] = []
new_trans_lines.append("/**")
new_trans_lines.append(" * Runtime translations map — built by spreading every dictionary under")
new_trans_lines.append(" * `./dictionaries/*`. Keep this file as the aggregation entry point;")
new_trans_lines.append(" * individual keys live in their domain files for easier editing.")
new_trans_lines.append(" */")
new_trans_lines.append("")
new_trans_lines.append("")
# Note: `Locale` is defined right above (line 7 in the original file) and stays
# in this file — we don't re-import it here.
for fname in written:
    stem = fname.removesuffix(".ts")
    # Strip hyphens so the local identifier is valid JS (e.g. `users-page` → `userspage`).
    var_stem = stem.replace("-", "")
    new_trans_lines.append(
        f'import {{ zh as {var_stem}Zh, en as {var_stem}En }} from "./dictionaries/{stem}";'
    )
new_trans_lines.append("")
new_trans_lines.append("const zh: Record<string, string> = {")
for fname in written:
    stem = fname.removesuffix(".ts")
    var_stem = stem.replace("-", "")
    new_trans_lines.append(f"\t...{var_stem}Zh,")
new_trans_lines.append("};")
new_trans_lines.append("")
new_trans_lines.append("const en: Record<string, string> = {")
for fname in written:
    stem = fname.removesuffix(".ts")
    var_stem = stem.replace("-", "")
    new_trans_lines.append(f"\t...{var_stem}En,")
new_trans_lines.append("};")
new_trans_lines.append("")
new_trans_lines.append("export const translations: Record<Locale, Record<string, string>> = {")
new_trans_lines.append("\tzh,")
new_trans_lines.append("\ten,")
new_trans_lines.append("};")
new_trans_lines.append("")

# Replace the original `const translations: Record<...> = { ... };` literal
# with the new aggregator import + spread form. The runtime `t` /
# `getAllTranslations` / `getServerLocale` helpers stay below — they read
# from this `translations` const via closure.
pattern = re.compile(
    r"^const translations:.*?\};",
    re.MULTILINE | re.DOTALL,
)
m = pattern.search(content)
if not m:
    print("[fail] could not locate `export const translations = { ... };`", file=sys.stderr)
    sys.exit(1)
new_content = content[: m.start()] + "\n".join(new_trans_lines).rstrip() + "\n" + content[m.end():]
TRANS_FILE.write_text(new_content, encoding="utf8")
print(f"[ok] rewrote translations.ts (entry point now imports {len(written)} dictionaries)")
print(f"[done] wrote {len(written)} dictionary files under {DICTS}")
