-- TR-031 E01: Cost tracking (manual input + daily snapshot + monthly summary).
--
-- Manual migration (not generated by `prisma migrate dev`) because the
-- development database has accumulated schema drift from earlier tasks
-- that is unrelated to E01 and would block an auto-generated diff. This
-- file therefore ONLY contains the E01 changes; the drift is left for a
-- separate housekeeping migration.
--
-- Models:
--   cost_entries  — itemized cost entries (vps / bandwidth / storage / other)
--                   each row = (provider, amount, effectiveDate).
--                   Multiple rows per month = sum gives monthly total.
--   cost_snapshots — one row per day, written by the daily snapshot job
--                    (scheduled 01:00 local). Captures MTD totals + per-category
--                    breakdown for trend charts.

CREATE TABLE "cost_entries" (
    "id" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'CNY',
    "effectiveDate" DATE NOT NULL,
    "notes" TEXT,
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "cost_entries_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "cost_snapshots" (
    "id" TEXT NOT NULL,
    "snapshotDate" DATE NOT NULL,
    "totalAmount" DECIMAL(14,2) NOT NULL,
    "byCategory" JSONB NOT NULL,
    "entryCount" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "cost_snapshots_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "cost_snapshots_snapshotDate_key" ON "cost_snapshots"("snapshotDate");
CREATE INDEX "cost_snapshots_snapshotDate_idx" ON "cost_snapshots"("snapshotDate");

CREATE INDEX "cost_entries_category_effectiveDate_idx" ON "cost_entries"("category", "effectiveDate");
CREATE INDEX "cost_entries_effectiveDate_idx" ON "cost_entries"("effectiveDate");
CREATE INDEX "cost_entries_createdById_effectiveDate_idx" ON "cost_entries"("createdById", "effectiveDate");

ALTER TABLE "cost_entries" ADD CONSTRAINT "cost_entries_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
